package field

import (
	"strings"

	"github.com/ddkwork/golibrary/std/stream"
)

// Code generated by EnumTypesGen - DO NOT EDIT.

type FieldType uint8

const (
	TextType FieldType = iota
	MultiLineTextType
	NumberType
	SingleSelectType
	MultipleSelectType
	DateTimeType
	FormulaType
	AttachmentType
	LinkType
	UserType
	PhoneType
	EmailType
	CheckboxType
	UrlType
	CurrencyType
	PercentType
)

func (t FieldType) Valid() bool {
	return t >= TextType && t <= PercentType
}

func FieldTypeBy[T stream.Integer](v T) FieldType {
	return FieldType(v)
}

func (t FieldType) AssertBy(name string) FieldType {
	name = strings.TrimSuffix(name, "Type")
	for _, n := range t.EnumTypes() {
		if strings.EqualFold(name, n.String()) {
			return n
		}
	}
	panic("InvalidType")
}

func (t FieldType) String() string {
	switch t {
	case TextType:
		return "Text"
	case MultiLineTextType:
		return "MultiLineText"
	case NumberType:
		return "Number"
	case SingleSelectType:
		return "SingleSelect"
	case MultipleSelectType:
		return "MultipleSelect"
	case DateTimeType:
		return "DateTime"
	case FormulaType:
		return "Formula"
	case AttachmentType:
		return "Attachment"
	case LinkType:
		return "Link"
	case UserType:
		return "User"
	case PhoneType:
		return "Phone"
	case EmailType:
		return "Email"
	case CheckboxType:
		return "Checkbox"
	case UrlType:
		return "Url"
	case CurrencyType:
		return "Currency"
	case PercentType:
		return "Percent"
	default:
		panic("InvalidType")
	}
}

func (t FieldType) Tooltip() string {
	switch t {
	case TextType:
		return "text"
	case MultiLineTextType:
		return "multiLineText"
	case NumberType:
		return "number"
	case SingleSelectType:
		return "singleSelect"
	case MultipleSelectType:
		return "multipleSelect"
	case DateTimeType:
		return "dateTime"
	case FormulaType:
		return "formula"
	case AttachmentType:
		return "attachment"
	case LinkType:
		return "link"
	case UserType:
		return "user"
	case PhoneType:
		return "phone"
	case EmailType:
		return "email"
	case CheckboxType:
		return "checkbox"
	case UrlType:
		return "url"
	case CurrencyType:
		return "currency"
	case PercentType:
		return "percent"
	default:
		panic("InvalidType")
	}
}

func (t FieldType) Names() []string {
	return []string{
		"Text",
		"MultiLineText",
		"Number",
		"SingleSelect",
		"MultipleSelect",
		"DateTime",
		"Formula",
		"Attachment",
		"Link",
		"User",
		"Phone",
		"Email",
		"Checkbox",
		"Url",
		"Currency",
		"Percent",
	}
}

func (t FieldType) EnumTypes() []FieldType {
	return []FieldType{
		TextType,
		MultiLineTextType,
		NumberType,
		SingleSelectType,
		MultipleSelectType,
		DateTimeType,
		FormulaType,
		AttachmentType,
		LinkType,
		UserType,
		PhoneType,
		EmailType,
		CheckboxType,
		UrlType,
		CurrencyType,
		PercentType,
	}
}

func (t FieldType) SvgFileName() string {
	return t.String() + ".svg"
}
