package ux

// generated by go generate; DO NOT EDIT.

import "image/color"

// Map contains named colors defined in the Theme Design style guide.
var Map = map[string]color.NRGBA{
	"Red50":          {0xff, 0xeb, 0xee, 0xff}, // rgb(255, 235, 238)
	"Red100":         {0xff, 0xcd, 0xd2, 0xff}, // rgb(255, 205, 210)
	"Red200":         {0xef, 0x9a, 0x9a, 0xff}, // rgb(239, 154, 154)
	"Red300":         {0xe5, 0x73, 0x73, 0xff}, // rgb(229, 115, 115)
	"Red400":         {0xef, 0x53, 0x50, 0xff}, // rgb(239, 83, 80)
	"Red500":         {0xf4, 0x43, 0x36, 0xff}, // rgb(244, 67, 54)
	"Red600":         {0xe5, 0x39, 0x35, 0xff}, // rgb(229, 57, 53)
	"Red700":         {0xd3, 0x2f, 0x2f, 0xff}, // rgb(211, 47, 47)
	"Red800":         {0xc6, 0x28, 0x28, 0xff}, // rgb(198, 40, 40)
	"Red900":         {0xb7, 0x1c, 0x1c, 0xff}, // rgb(183, 28, 28)
	"RedA100":        {0xff, 0x8a, 0x80, 0xff}, // rgb(255, 138, 128)
	"RedA200":        {0xff, 0x52, 0x52, 0xff}, // rgb(255, 82, 82)
	"RedA400":        {0xff, 0x17, 0x44, 0xff}, // rgb(255, 23, 68)
	"RedA700":        {0xd5, 0x00, 0x00, 0xff}, // rgb(213, 0, 0)
	"Pink50":         {0xfc, 0xe4, 0xec, 0xff}, // rgb(252, 228, 236)
	"Pink100":        {0xf8, 0xbb, 0xd0, 0xff}, // rgb(248, 187, 208)
	"Pink200":        {0xf4, 0x8f, 0xb1, 0xff}, // rgb(244, 143, 177)
	"Pink300":        {0xf0, 0x62, 0x92, 0xff}, // rgb(240, 98, 146)
	"Pink400":        {0xec, 0x40, 0x7a, 0xff}, // rgb(236, 64, 122)
	"Pink500":        {0xe9, 0x1e, 0x63, 0xff}, // rgb(233, 30, 99)
	"Pink600":        {0xd8, 0x1b, 0x60, 0xff}, // rgb(216, 27, 96)
	"Pink700":        {0xc2, 0x18, 0x5b, 0xff}, // rgb(194, 24, 91)
	"Pink800":        {0xad, 0x14, 0x57, 0xff}, // rgb(173, 20, 87)
	"Pink900":        {0x88, 0x0e, 0x4f, 0xff}, // rgb(136, 14, 79)
	"PinkA100":       {0xff, 0x80, 0xab, 0xff}, // rgb(255, 128, 171)
	"PinkA200":       {0xff, 0x40, 0x81, 0xff}, // rgb(255, 64, 129)
	"PinkA400":       {0xf5, 0x00, 0x57, 0xff}, // rgb(245, 0, 87)
	"PinkA700":       {0xc5, 0x11, 0x62, 0xff}, // rgb(197, 17, 98)
	"Purple50":       {0xf3, 0xe5, 0xf5, 0xff}, // rgb(243, 229, 245)
	"Purple100":      {0xe1, 0xbe, 0xe7, 0xff}, // rgb(225, 190, 231)
	"Purple200":      {0xce, 0x93, 0xd8, 0xff}, // rgb(206, 147, 216)
	"Purple300":      {0xba, 0x68, 0xc8, 0xff}, // rgb(186, 104, 200)
	"Purple400":      {0xab, 0x47, 0xbc, 0xff}, // rgb(171, 71, 188)
	"Purple500":      {0x9c, 0x27, 0xb0, 0xff}, // rgb(156, 39, 176)
	"Purple600":      {0x8e, 0x24, 0xaa, 0xff}, // rgb(142, 36, 170)
	"Purple700":      {0x7b, 0x1f, 0xa2, 0xff}, // rgb(123, 31, 162)
	"Purple800":      {0x6a, 0x1b, 0x9a, 0xff}, // rgb(106, 27, 154)
	"Purple900":      {0x4a, 0x14, 0x8c, 0xff}, // rgb(74, 20, 140)
	"PurpleA100":     {0xea, 0x80, 0xfc, 0xff}, // rgb(234, 128, 252)
	"PurpleA200":     {0xe0, 0x40, 0xfb, 0xff}, // rgb(224, 64, 251)
	"PurpleA400":     {0xd5, 0x00, 0xf9, 0xff}, // rgb(213, 0, 249)
	"PurpleA700":     {0xaa, 0x00, 0xff, 0xff}, // rgb(170, 0, 255)
	"DeepPurple50":   {0xed, 0xe7, 0xf6, 0xff}, // rgb(237, 231, 246)
	"DeepPurple100":  {0xd1, 0xc4, 0xe9, 0xff}, // rgb(209, 196, 233)
	"DeepPurple200":  {0xb3, 0x9d, 0xdb, 0xff}, // rgb(179, 157, 219)
	"DeepPurple300":  {0x95, 0x75, 0xcd, 0xff}, // rgb(149, 117, 205)
	"DeepPurple400":  {0x7e, 0x57, 0xc2, 0xff}, // rgb(126, 87, 194)
	"DeepPurple500":  {0x67, 0x3a, 0xb7, 0xff}, // rgb(103, 58, 183)
	"DeepPurple600":  {0x5e, 0x35, 0xb1, 0xff}, // rgb(94, 53, 177)
	"DeepPurple700":  {0x51, 0x2d, 0xa8, 0xff}, // rgb(81, 45, 168)
	"DeepPurple800":  {0x45, 0x27, 0xa0, 0xff}, // rgb(69, 39, 160)
	"DeepPurple900":  {0x31, 0x1b, 0x92, 0xff}, // rgb(49, 27, 146)
	"DeepPurpleA100": {0xb3, 0x88, 0xff, 0xff}, // rgb(179, 136, 255)
	"DeepPurpleA200": {0x7c, 0x4d, 0xff, 0xff}, // rgb(124, 77, 255)
	"DeepPurpleA400": {0x65, 0x1f, 0xff, 0xff}, // rgb(101, 31, 255)
	"DeepPurpleA700": {0x62, 0x00, 0xea, 0xff}, // rgb(98, 0, 234)
	"Indigo50":       {0xe8, 0xea, 0xf6, 0xff}, // rgb(232, 234, 246)
	"Indigo100":      {0xc5, 0xca, 0xe9, 0xff}, // rgb(197, 202, 233)
	"Indigo200":      {0x9f, 0xa8, 0xda, 0xff}, // rgb(159, 168, 218)
	"Indigo300":      {0x79, 0x86, 0xcb, 0xff}, // rgb(121, 134, 203)
	"Indigo400":      {0x5c, 0x6b, 0xc0, 0xff}, // rgb(92, 107, 192)
	"Indigo500":      {0x3f, 0x51, 0xb5, 0xff}, // rgb(63, 81, 181)
	"Indigo600":      {0x39, 0x49, 0xab, 0xff}, // rgb(57, 73, 171)
	"Indigo700":      {0x30, 0x3f, 0x9f, 0xff}, // rgb(48, 63, 159)
	"Indigo800":      {0x28, 0x35, 0x93, 0xff}, // rgb(40, 53, 147)
	"Indigo900":      {0x1a, 0x23, 0x7e, 0xff}, // rgb(26, 35, 126)
	"IndigoA100":     {0x8c, 0x9e, 0xff, 0xff}, // rgb(140, 158, 255)
	"IndigoA200":     {0x53, 0x6d, 0xfe, 0xff}, // rgb(83, 109, 254)
	"IndigoA400":     {0x3d, 0x5a, 0xfe, 0xff}, // rgb(61, 90, 254)
	"IndigoA700":     {0x30, 0x4f, 0xfe, 0xff}, // rgb(48, 79, 254)
	"Blue50":         {0xe3, 0xf2, 0xfd, 0xff}, // rgb(227, 242, 253)
	"Blue100":        {0xbb, 0xde, 0xfb, 0xff}, // rgb(187, 222, 251)
	"Blue200":        {0x90, 0xca, 0xf9, 0xff}, // rgb(144, 202, 249)
	"Blue300":        {0x64, 0xb5, 0xf6, 0xff}, // rgb(100, 181, 246)
	"Blue400":        {0x42, 0xa5, 0xf5, 0xff}, // rgb(66, 165, 245)
	"Blue500":        {0x21, 0x96, 0xf3, 0xff}, // rgb(33, 150, 243)
	"Blue600":        {0x1e, 0x88, 0xe5, 0xff}, // rgb(30, 136, 229)
	"Blue700":        {0x19, 0x76, 0xd2, 0xff}, // rgb(25, 118, 210)
	"Blue800":        {0x15, 0x65, 0xc0, 0xff}, // rgb(21, 101, 192)
	"Blue900":        {0x0d, 0x47, 0xa1, 0xff}, // rgb(13, 71, 161)
	"BlueA100":       {0x82, 0xb1, 0xff, 0xff}, // rgb(130, 177, 255)
	"BlueA200":       {0x44, 0x8a, 0xff, 0xff}, // rgb(68, 138, 255)
	"BlueA400":       {0x29, 0x79, 0xff, 0xff}, // rgb(41, 121, 255)
	"BlueA700":       {0x29, 0x62, 0xff, 0xff}, // rgb(41, 98, 255)
	"LightBlue50":    {0xe1, 0xf5, 0xfe, 0xff}, // rgb(225, 245, 254)
	"LightBlue100":   {0xb3, 0xe5, 0xfc, 0xff}, // rgb(179, 229, 252)
	"LightBlue200":   {0x81, 0xd4, 0xfa, 0xff}, // rgb(129, 212, 250)
	"LightBlue300":   {0x4f, 0xc3, 0xf7, 0xff}, // rgb(79, 195, 247)
	"LightBlue400":   {0x29, 0xb6, 0xf6, 0xff}, // rgb(41, 182, 246)
	"LightBlue500":   {0x03, 0xa9, 0xf4, 0xff}, // rgb(3, 169, 244)
	"LightBlue600":   {0x03, 0x9b, 0xe5, 0xff}, // rgb(3, 155, 229)
	"LightBlue700":   {0x02, 0x88, 0xd1, 0xff}, // rgb(2, 136, 209)
	"LightBlue800":   {0x02, 0x77, 0xbd, 0xff}, // rgb(2, 119, 189)
	"LightBlue900":   {0x01, 0x57, 0x9b, 0xff}, // rgb(1, 87, 155)
	"LightBlueA100":  {0x80, 0xd8, 0xff, 0xff}, // rgb(128, 216, 255)
	"LightBlueA200":  {0x40, 0xc4, 0xff, 0xff}, // rgb(64, 196, 255)
	"LightBlueA400":  {0x00, 0xb0, 0xff, 0xff}, // rgb(0, 176, 255)
	"LightBlueA700":  {0x00, 0x91, 0xea, 0xff}, // rgb(0, 145, 234)
	"Cyan50":         {0xe0, 0xf7, 0xfa, 0xff}, // rgb(224, 247, 250)
	"Cyan100":        {0xb2, 0xeb, 0xf2, 0xff}, // rgb(178, 235, 242)
	"Cyan200":        {0x80, 0xde, 0xea, 0xff}, // rgb(128, 222, 234)
	"Cyan300":        {0x4d, 0xd0, 0xe1, 0xff}, // rgb(77, 208, 225)
	"Cyan400":        {0x26, 0xc6, 0xda, 0xff}, // rgb(38, 198, 218)
	"Cyan500":        {0x00, 0xbc, 0xd4, 0xff}, // rgb(0, 188, 212)
	"Cyan600":        {0x00, 0xac, 0xc1, 0xff}, // rgb(0, 172, 193)
	"Cyan700":        {0x00, 0x97, 0xa7, 0xff}, // rgb(0, 151, 167)
	"Cyan800":        {0x00, 0x83, 0x8f, 0xff}, // rgb(0, 131, 143)
	"Cyan900":        {0x00, 0x60, 0x64, 0xff}, // rgb(0, 96, 100)
	"CyanA100":       {0x84, 0xff, 0xff, 0xff}, // rgb(132, 255, 255)
	"CyanA200":       {0x18, 0xff, 0xff, 0xff}, // rgb(24, 255, 255)
	"CyanA400":       {0x00, 0xe5, 0xff, 0xff}, // rgb(0, 229, 255)
	"CyanA700":       {0x00, 0xb8, 0xd4, 0xff}, // rgb(0, 184, 212)
	"Teal50":         {0xe0, 0xf2, 0xf1, 0xff}, // rgb(224, 242, 241)
	"Teal100":        {0xb2, 0xdf, 0xdb, 0xff}, // rgb(178, 223, 219)
	"Teal200":        {0x80, 0xcb, 0xc4, 0xff}, // rgb(128, 203, 196)
	"Teal300":        {0x4d, 0xb6, 0xac, 0xff}, // rgb(77, 182, 172)
	"Teal400":        {0x26, 0xa6, 0x9a, 0xff}, // rgb(38, 166, 154)
	"Teal500":        {0x00, 0x96, 0x88, 0xff}, // rgb(0, 150, 136)
	"Teal600":        {0x00, 0x89, 0x7b, 0xff}, // rgb(0, 137, 123)
	"Teal700":        {0x00, 0x79, 0x6b, 0xff}, // rgb(0, 121, 107)
	"Teal800":        {0x00, 0x69, 0x5c, 0xff}, // rgb(0, 105, 92)
	"Teal900":        {0x00, 0x4d, 0x40, 0xff}, // rgb(0, 77, 64)
	"TealA100":       {0xa7, 0xff, 0xeb, 0xff}, // rgb(167, 255, 235)
	"TealA200":       {0x64, 0xff, 0xda, 0xff}, // rgb(100, 255, 218)
	"TealA400":       {0x1d, 0xe9, 0xb6, 0xff}, // rgb(29, 233, 182)
	"TealA700":       {0x00, 0xbf, 0xa5, 0xff}, // rgb(0, 191, 165)
	"Green50":        {0xe8, 0xf5, 0xe9, 0xff}, // rgb(232, 245, 233)
	"Green100":       {0xc8, 0xe6, 0xc9, 0xff}, // rgb(200, 230, 201)
	"Green200":       {0xa5, 0xd6, 0xa7, 0xff}, // rgb(165, 214, 167)
	"Green300":       {0x81, 0xc7, 0x84, 0xff}, // rgb(129, 199, 132)
	"Green400":       {0x66, 0xbb, 0x6a, 0xff}, // rgb(102, 187, 106)
	"Green500":       {0x4c, 0xaf, 0x50, 0xff}, // rgb(76, 175, 80)
	"Green600":       {0x43, 0xa0, 0x47, 0xff}, // rgb(67, 160, 71)
	"Green700":       {0x38, 0x8e, 0x3c, 0xff}, // rgb(56, 142, 60)
	"Green800":       {0x2e, 0x7d, 0x32, 0xff}, // rgb(46, 125, 50)
	"Green900":       {0x1b, 0x5e, 0x20, 0xff}, // rgb(27, 94, 32)
	"GreenA100":      {0xb9, 0xf6, 0xca, 0xff}, // rgb(185, 246, 202)
	"GreenA200":      {0x69, 0xf0, 0xae, 0xff}, // rgb(105, 240, 174)
	"GreenA400":      {0x00, 0xe6, 0x76, 0xff}, // rgb(0, 230, 118)
	"GreenA700":      {0x00, 0xc8, 0x53, 0xff}, // rgb(0, 200, 83)
	"LightGreen50":   {0xf1, 0xf8, 0xe9, 0xff}, // rgb(241, 248, 233)
	"LightGreen100":  {0xdc, 0xed, 0xc8, 0xff}, // rgb(220, 237, 200)
	"LightGreen200":  {0xc5, 0xe1, 0xa5, 0xff}, // rgb(197, 225, 165)
	"LightGreen300":  {0xae, 0xd5, 0x81, 0xff}, // rgb(174, 213, 129)
	"LightGreen400":  {0x9c, 0xcc, 0x65, 0xff}, // rgb(156, 204, 101)
	"LightGreen500":  {0x8b, 0xc3, 0x4a, 0xff}, // rgb(139, 195, 74)
	"LightGreen600":  {0x7c, 0xb3, 0x42, 0xff}, // rgb(124, 179, 66)
	"LightGreen700":  {0x68, 0x9f, 0x38, 0xff}, // rgb(104, 159, 56)
	"LightGreen800":  {0x55, 0x8b, 0x2f, 0xff}, // rgb(85, 139, 47)
	"LightGreen900":  {0x33, 0x69, 0x1e, 0xff}, // rgb(51, 105, 30)
	"LightGreenA100": {0xcc, 0xff, 0x90, 0xff}, // rgb(204, 255, 144)
	"LightGreenA200": {0xb2, 0xff, 0x59, 0xff}, // rgb(178, 255, 89)
	"LightGreenA400": {0x76, 0xff, 0x03, 0xff}, // rgb(118, 255, 3)
	"LightGreenA700": {0x64, 0xdd, 0x17, 0xff}, // rgb(100, 221, 23)
	"Lime50":         {0xf9, 0xfb, 0xe7, 0xff}, // rgb(249, 251, 231)
	"Lime100":        {0xf0, 0xf4, 0xc3, 0xff}, // rgb(240, 244, 195)
	"Lime200":        {0xe6, 0xee, 0x9c, 0xff}, // rgb(230, 238, 156)
	"Lime300":        {0xdc, 0xe7, 0x75, 0xff}, // rgb(220, 231, 117)
	"Lime400":        {0xd4, 0xe1, 0x57, 0xff}, // rgb(212, 225, 87)
	"Lime500":        {0xcd, 0xdc, 0x39, 0xff}, // rgb(205, 220, 57)
	"Lime600":        {0xc0, 0xca, 0x33, 0xff}, // rgb(192, 202, 51)
	"Lime700":        {0xaf, 0xb4, 0x2b, 0xff}, // rgb(175, 180, 43)
	"Lime800":        {0x9e, 0x9d, 0x24, 0xff}, // rgb(158, 157, 36)
	"Lime900":        {0x82, 0x77, 0x17, 0xff}, // rgb(130, 119, 23)
	"LimeA100":       {0xf4, 0xff, 0x81, 0xff}, // rgb(244, 255, 129)
	"LimeA200":       {0xee, 0xff, 0x41, 0xff}, // rgb(238, 255, 65)
	"LimeA400":       {0xc6, 0xff, 0x00, 0xff}, // rgb(198, 255, 0)
	"LimeA700":       {0xae, 0xea, 0x00, 0xff}, // rgb(174, 234, 0)
	"Yellow50":       {0xff, 0xfd, 0xe7, 0xff}, // rgb(255, 253, 231)
	"Yellow100":      {0xff, 0xf9, 0xc4, 0xff}, // rgb(255, 249, 196)
	"Yellow200":      {0xff, 0xf5, 0x9d, 0xff}, // rgb(255, 245, 157)
	"Yellow300":      {0xff, 0xf1, 0x76, 0xff}, // rgb(255, 241, 118)
	"Yellow400":      {0xff, 0xee, 0x58, 0xff}, // rgb(255, 238, 88)
	"Yellow500":      {0xff, 0xeb, 0x3b, 0xff}, // rgb(255, 235, 59)
	"Yellow600":      {0xfd, 0xd8, 0x35, 0xff}, // rgb(253, 216, 53)
	"Yellow700":      {0xfb, 0xc0, 0x2d, 0xff}, // rgb(251, 192, 45)
	"Yellow800":      {0xf9, 0xa8, 0x25, 0xff}, // rgb(249, 168, 37)
	"Yellow900":      {0xf5, 0x7f, 0x17, 0xff}, // rgb(245, 127, 23)
	"YellowA100":     {0xff, 0xff, 0x8d, 0xff}, // rgb(255, 255, 141)
	"YellowA200":     {0xff, 0xff, 0x00, 0xff}, // rgb(255, 255, 0)
	"YellowA400":     {0xff, 0xea, 0x00, 0xff}, // rgb(255, 234, 0)
	"YellowA700":     {0xff, 0xd6, 0x00, 0xff}, // rgb(255, 214, 0)
	"Amber50":        {0xff, 0xf8, 0xe1, 0xff}, // rgb(255, 248, 225)
	"Amber100":       {0xff, 0xec, 0xb3, 0xff}, // rgb(255, 236, 179)
	"Amber200":       {0xff, 0xe0, 0x82, 0xff}, // rgb(255, 224, 130)
	"Amber300":       {0xff, 0xd5, 0x4f, 0xff}, // rgb(255, 213, 79)
	"Amber400":       {0xff, 0xca, 0x28, 0xff}, // rgb(255, 202, 40)
	"Amber500":       {0xff, 0xc1, 0x07, 0xff}, // rgb(255, 193, 7)
	"Amber600":       {0xff, 0xb3, 0x00, 0xff}, // rgb(255, 179, 0)
	"Amber700":       {0xff, 0xa0, 0x00, 0xff}, // rgb(255, 160, 0)
	"Amber800":       {0xff, 0x8f, 0x00, 0xff}, // rgb(255, 143, 0)
	"Amber900":       {0xff, 0x6f, 0x00, 0xff}, // rgb(255, 111, 0)
	"AmberA100":      {0xff, 0xe5, 0x7f, 0xff}, // rgb(255, 229, 127)
	"AmberA200":      {0xff, 0xd7, 0x40, 0xff}, // rgb(255, 215, 64)
	"AmberA400":      {0xff, 0xc4, 0x00, 0xff}, // rgb(255, 196, 0)
	"AmberA700":      {0xff, 0xab, 0x00, 0xff}, // rgb(255, 171, 0)
	"Orange50":       {0xff, 0xf3, 0xe0, 0xff}, // rgb(255, 243, 224)
	"Orange100":      {0xff, 0xe0, 0xb2, 0xff}, // rgb(255, 224, 178)
	"Orange200":      {0xff, 0xcc, 0x80, 0xff}, // rgb(255, 204, 128)
	"Orange300":      {0xff, 0xb7, 0x4d, 0xff}, // rgb(255, 183, 77)
	"Orange400":      {0xff, 0xa7, 0x26, 0xff}, // rgb(255, 167, 38)
	"Orange500":      {0xff, 0x98, 0x00, 0xff}, // rgb(255, 152, 0)
	"Orange600":      {0xfb, 0x8c, 0x00, 0xff}, // rgb(251, 140, 0)
	"Orange700":      {0xf5, 0x7c, 0x00, 0xff}, // rgb(245, 124, 0)
	"Orange800":      {0xef, 0x6c, 0x00, 0xff}, // rgb(239, 108, 0)
	"Orange900":      {0xe6, 0x51, 0x00, 0xff}, // rgb(230, 81, 0)
	"OrangeA100":     {0xff, 0xd1, 0x80, 0xff}, // rgb(255, 209, 128)
	"OrangeA200":     {0xff, 0xab, 0x40, 0xff}, // rgb(255, 171, 64)
	"OrangeA400":     {0xff, 0x91, 0x00, 0xff}, // rgb(255, 145, 0)
	"OrangeA700":     {0xff, 0x6d, 0x00, 0xff}, // rgb(255, 109, 0)
	"DeepOrange50":   {0xfb, 0xe9, 0xe7, 0xff}, // rgb(251, 233, 231)
	"DeepOrange100":  {0xff, 0xcc, 0xbc, 0xff}, // rgb(255, 204, 188)
	"DeepOrange200":  {0xff, 0xab, 0x91, 0xff}, // rgb(255, 171, 145)
	"DeepOrange300":  {0xff, 0x8a, 0x65, 0xff}, // rgb(255, 138, 101)
	"DeepOrange400":  {0xff, 0x70, 0x43, 0xff}, // rgb(255, 112, 67)
	"DeepOrange500":  {0xff, 0x57, 0x22, 0xff}, // rgb(255, 87, 34)
	"DeepOrange600":  {0xf4, 0x51, 0x1e, 0xff}, // rgb(244, 81, 30)
	"DeepOrange700":  {0xe6, 0x4a, 0x19, 0xff}, // rgb(230, 74, 25)
	"DeepOrange800":  {0xd8, 0x43, 0x15, 0xff}, // rgb(216, 67, 21)
	"DeepOrange900":  {0xbf, 0x36, 0x0c, 0xff}, // rgb(191, 54, 12)
	"DeepOrangeA100": {0xff, 0x9e, 0x80, 0xff}, // rgb(255, 158, 128)
	"DeepOrangeA200": {0xff, 0x6e, 0x40, 0xff}, // rgb(255, 110, 64)
	"DeepOrangeA400": {0xff, 0x3d, 0x00, 0xff}, // rgb(255, 61, 0)
	"DeepOrangeA700": {0xdd, 0x2c, 0x00, 0xff}, // rgb(221, 44, 0)
	"Brown50":        {0xef, 0xeb, 0xe9, 0xff}, // rgb(239, 235, 233)
	"Brown100":       {0xd7, 0xcc, 0xc8, 0xff}, // rgb(215, 204, 200)
	"Brown200":       {0xbc, 0xaa, 0xa4, 0xff}, // rgb(188, 170, 164)
	"Brown300":       {0xa1, 0x88, 0x7f, 0xff}, // rgb(161, 136, 127)
	"Brown400":       {0x8d, 0x6e, 0x63, 0xff}, // rgb(141, 110, 99)
	"Brown500":       {0x79, 0x55, 0x48, 0xff}, // rgb(121, 85, 72)
	"Brown600":       {0x6d, 0x4c, 0x41, 0xff}, // rgb(109, 76, 65)
	"Brown700":       {0x5d, 0x40, 0x37, 0xff}, // rgb(93, 64, 55)
	"Brown800":       {0x4e, 0x34, 0x2e, 0xff}, // rgb(78, 52, 46)
	"Brown900":       {0x3e, 0x27, 0x23, 0xff}, // rgb(62, 39, 35)
	"Grey50":         {0xfa, 0xfa, 0xfa, 0xff}, // rgb(250, 250, 250)
	"Grey100":        {0xf5, 0xf5, 0xf5, 0xff}, // rgb(245, 245, 245)
	"Grey200":        {0xee, 0xee, 0xee, 0xff}, // rgb(238, 238, 238)
	"Grey300":        {0xe0, 0xe0, 0xe0, 0xff}, // rgb(224, 224, 224)
	"Grey400":        {0xbd, 0xbd, 0xbd, 0xff}, // rgb(189, 189, 189)
	"Grey500":        {0x9e, 0x9e, 0x9e, 0xff}, // rgb(158, 158, 158)
	"Grey600":        {0x75, 0x75, 0x75, 0xff}, // rgb(117, 117, 117)
	"Grey700":        {0x61, 0x61, 0x61, 0xff}, // rgb(97, 97, 97)
	"Grey800":        {0x42, 0x42, 0x42, 0xff}, // rgb(66, 66, 66)
	"Grey900":        {0x21, 0x21, 0x21, 0xff}, // rgb(33, 33, 33)
	"BlueGrey50":     {0xec, 0xef, 0xf1, 0xff}, // rgb(236, 239, 241)
	"BlueGrey100":    {0xcf, 0xd8, 0xdc, 0xff}, // rgb(207, 216, 220)
	"BlueGrey200":    {0xb0, 0xbe, 0xc5, 0xff}, // rgb(176, 190, 197)
	"BlueGrey300":    {0x90, 0xa4, 0xae, 0xff}, // rgb(144, 164, 174)
	"BlueGrey400":    {0x78, 0x90, 0x9c, 0xff}, // rgb(120, 144, 156)
	"BlueGrey500":    {0x60, 0x7d, 0x8b, 0xff}, // rgb(96, 125, 139)
	"BlueGrey600":    {0x54, 0x6e, 0x7a, 0xff}, // rgb(84, 110, 122)
	"BlueGrey700":    {0x45, 0x5a, 0x64, 0xff}, // rgb(69, 90, 100)
	"BlueGrey800":    {0x37, 0x47, 0x4f, 0xff}, // rgb(55, 71, 79)
	"BlueGrey900":    {0x26, 0x32, 0x38, 0xff}, // rgb(38, 50, 56)
	"Black":          {0x00, 0x00, 0x00, 0xff}, // rgb(0, 0, 0)
	"White":          {0xff, 0xff, 0xff, 0xff}, // rgb(255, 255, 255)
}

// Names contains the color names defined in the Theme Design style guide.
var Names = []string{
	"Red50",
	"Red100",
	"Red200",
	"Red300",
	"Red400",
	"Red500",
	"Red600",
	"Red700",
	"Red800",
	"Red900",
	"RedA100",
	"RedA200",
	"RedA400",
	"RedA700",
	"Pink50",
	"Pink100",
	"Pink200",
	"Pink300",
	"Pink400",
	"Pink500",
	"Pink600",
	"Pink700",
	"Pink800",
	"Pink900",
	"PinkA100",
	"PinkA200",
	"PinkA400",
	"PinkA700",
	"Purple50",
	"Purple100",
	"Purple200",
	"Purple300",
	"Purple400",
	"Purple500",
	"Purple600",
	"Purple700",
	"Purple800",
	"Purple900",
	"PurpleA100",
	"PurpleA200",
	"PurpleA400",
	"PurpleA700",
	"DeepPurple50",
	"DeepPurple100",
	"DeepPurple200",
	"DeepPurple300",
	"DeepPurple400",
	"DeepPurple500",
	"DeepPurple600",
	"DeepPurple700",
	"DeepPurple800",
	"DeepPurple900",
	"DeepPurpleA100",
	"DeepPurpleA200",
	"DeepPurpleA400",
	"DeepPurpleA700",
	"Indigo50",
	"Indigo100",
	"Indigo200",
	"Indigo300",
	"Indigo400",
	"Indigo500",
	"Indigo600",
	"Indigo700",
	"Indigo800",
	"Indigo900",
	"IndigoA100",
	"IndigoA200",
	"IndigoA400",
	"IndigoA700",
	"Blue50",
	"Blue100",
	"Blue200",
	"Blue300",
	"Blue400",
	"Blue500",
	"Blue600",
	"Blue700",
	"Blue800",
	"Blue900",
	"BlueA100",
	"BlueA200",
	"BlueA400",
	"BlueA700",
	"LightBlue50",
	"LightBlue100",
	"LightBlue200",
	"LightBlue300",
	"LightBlue400",
	"LightBlue500",
	"LightBlue600",
	"LightBlue700",
	"LightBlue800",
	"LightBlue900",
	"LightBlueA100",
	"LightBlueA200",
	"LightBlueA400",
	"LightBlueA700",
	"Cyan50",
	"Cyan100",
	"Cyan200",
	"Cyan300",
	"Cyan400",
	"Cyan500",
	"Cyan600",
	"Cyan700",
	"Cyan800",
	"Cyan900",
	"CyanA100",
	"CyanA200",
	"CyanA400",
	"CyanA700",
	"Teal50",
	"Teal100",
	"Teal200",
	"Teal300",
	"Teal400",
	"Teal500",
	"Teal600",
	"Teal700",
	"Teal800",
	"Teal900",
	"TealA100",
	"TealA200",
	"TealA400",
	"TealA700",
	"Green50",
	"Green100",
	"Green200",
	"Green300",
	"Green400",
	"Green500",
	"Green600",
	"Green700",
	"Green800",
	"Green900",
	"GreenA100",
	"GreenA200",
	"GreenA400",
	"GreenA700",
	"LightGreen50",
	"LightGreen100",
	"LightGreen200",
	"LightGreen300",
	"LightGreen400",
	"LightGreen500",
	"LightGreen600",
	"LightGreen700",
	"LightGreen800",
	"LightGreen900",
	"LightGreenA100",
	"LightGreenA200",
	"LightGreenA400",
	"LightGreenA700",
	"Lime50",
	"Lime100",
	"Lime200",
	"Lime300",
	"Lime400",
	"Lime500",
	"Lime600",
	"Lime700",
	"Lime800",
	"Lime900",
	"LimeA100",
	"LimeA200",
	"LimeA400",
	"LimeA700",
	"Yellow50",
	"Yellow100",
	"Yellow200",
	"Yellow300",
	"Yellow400",
	"Yellow500",
	"Yellow600",
	"Yellow700",
	"Yellow800",
	"Yellow900",
	"YellowA100",
	"YellowA200",
	"YellowA400",
	"YellowA700",
	"Amber50",
	"Amber100",
	"Amber200",
	"Amber300",
	"Amber400",
	"Amber500",
	"Amber600",
	"Amber700",
	"Amber800",
	"Amber900",
	"AmberA100",
	"AmberA200",
	"AmberA400",
	"AmberA700",
	"Orange50",
	"Orange100",
	"Orange200",
	"Orange300",
	"Orange400",
	"Orange500",
	"Orange600",
	"Orange700",
	"Orange800",
	"Orange900",
	"OrangeA100",
	"OrangeA200",
	"OrangeA400",
	"OrangeA700",
	"DeepOrange50",
	"DeepOrange100",
	"DeepOrange200",
	"DeepOrange300",
	"DeepOrange400",
	"DeepOrange500",
	"DeepOrange600",
	"DeepOrange700",
	"DeepOrange800",
	"DeepOrange900",
	"DeepOrangeA100",
	"DeepOrangeA200",
	"DeepOrangeA400",
	"DeepOrangeA700",
	"Brown50",
	"Brown100",
	"Brown200",
	"Brown300",
	"Brown400",
	"Brown500",
	"Brown600",
	"Brown700",
	"Brown800",
	"Brown900",
	"Grey50",
	"Grey100",
	"Grey200",
	"Grey300",
	"Grey400",
	"Grey500",
	"Grey600",
	"Grey700",
	"Grey800",
	"Grey900",
	"BlueGrey50",
	"BlueGrey100",
	"BlueGrey200",
	"BlueGrey300",
	"BlueGrey400",
	"BlueGrey500",
	"BlueGrey600",
	"BlueGrey700",
	"BlueGrey800",
	"BlueGrey900",
	"Black",
	"White",
}

var (
	Red50           = color.NRGBA{R: 0xff, G: 0xeb, B: 0xee, A: 0xff} // rgb(255, 235, 238)
	Red100          = color.NRGBA{R: 0xff, G: 0xcd, B: 0xd2, A: 0xff} // rgb(255, 205, 210)
	Red200          = color.NRGBA{R: 0xef, G: 0x9a, B: 0x9a, A: 0xff} // rgb(239, 154, 154)
	Red300          = color.NRGBA{R: 0xe5, G: 0x73, B: 0x73, A: 0xff} // rgb(229, 115, 115)
	Red400          = color.NRGBA{R: 0xef, G: 0x53, B: 0x50, A: 0xff} // rgb(239, 83, 80)
	Red500          = color.NRGBA{R: 0xf4, G: 0x43, B: 0x36, A: 0xff} // rgb(244, 67, 54)
	Red600          = color.NRGBA{R: 0xe5, G: 0x39, B: 0x35, A: 0xff} // rgb(229, 57, 53)
	Red700          = color.NRGBA{R: 0xd3, G: 0x2f, B: 0x2f, A: 0xff} // rgb(211, 47, 47)
	Red800          = color.NRGBA{R: 0xc6, G: 0x28, B: 0x28, A: 0xff} // rgb(198, 40, 40)
	Red900          = color.NRGBA{R: 0xb7, G: 0x1c, B: 0x1c, A: 0xff} // rgb(183, 28, 28)
	RedA100         = color.NRGBA{R: 0xff, G: 0x8a, B: 0x80, A: 0xff} // rgb(255, 138, 128)
	RedA200         = color.NRGBA{R: 0xff, G: 0x52, B: 0x52, A: 0xff} // rgb(255, 82, 82)
	RedA400         = color.NRGBA{R: 0xff, G: 0x17, B: 0x44, A: 0xff} // rgb(255, 23, 68)
	RedA700         = color.NRGBA{R: 0xd5, A: 0xff}                   // rgb(213, 0, 0)
	Pink50          = color.NRGBA{R: 0xfc, G: 0xe4, B: 0xec, A: 0xff} // rgb(252, 228, 236)
	Pink100         = color.NRGBA{R: 0xf8, G: 0xbb, B: 0xd0, A: 0xff} // rgb(248, 187, 208)
	Pink200         = color.NRGBA{R: 0xf4, G: 0x8f, B: 0xb1, A: 0xff} // rgb(244, 143, 177)
	Pink300         = color.NRGBA{R: 0xf0, G: 0x62, B: 0x92, A: 0xff} // rgb(240, 98, 146)
	Pink400         = color.NRGBA{R: 0xec, G: 0x40, B: 0x7a, A: 0xff} // rgb(236, 64, 122)
	Pink500         = color.NRGBA{R: 0xe9, G: 0x1e, B: 0x63, A: 0xff} // rgb(233, 30, 99)
	Pink600         = color.NRGBA{R: 0xd8, G: 0x1b, B: 0x60, A: 0xff} // rgb(216, 27, 96)
	Pink700         = color.NRGBA{R: 0xc2, G: 0x18, B: 0x5b, A: 0xff} // rgb(194, 24, 91)
	Pink800         = color.NRGBA{R: 0xad, G: 0x14, B: 0x57, A: 0xff} // rgb(173, 20, 87)
	Pink900         = color.NRGBA{R: 0x88, G: 0x0e, B: 0x4f, A: 0xff} // rgb(136, 14, 79)
	PinkA100        = color.NRGBA{R: 0xff, G: 0x80, B: 0xab, A: 0xff} // rgb(255, 128, 171)
	PinkA200        = color.NRGBA{R: 0xff, G: 0x40, B: 0x81, A: 0xff} // rgb(255, 64, 129)
	PinkA400        = color.NRGBA{R: 0xf5, B: 0x57, A: 0xff}          // rgb(245, 0, 87)
	PinkA700        = color.NRGBA{R: 0xc5, G: 0x11, B: 0x62, A: 0xff} // rgb(197, 17, 98)
	Purple50        = color.NRGBA{R: 0xf3, G: 0xe5, B: 0xf5, A: 0xff} // rgb(243, 229, 245)
	Purple100       = color.NRGBA{R: 0xe1, G: 0xbe, B: 0xe7, A: 0xff} // rgb(225, 190, 231)
	Purple200       = color.NRGBA{R: 0xce, G: 0x93, B: 0xd8, A: 0xff} // rgb(206, 147, 216)
	Purple300       = color.NRGBA{R: 0xba, G: 0x68, B: 0xc8, A: 0xff} // rgb(186, 104, 200)
	Purple400       = color.NRGBA{R: 0xab, G: 0x47, B: 0xbc, A: 0xff} // rgb(171, 71, 188)
	Purple500       = color.NRGBA{R: 0x9c, G: 0x27, B: 0xb0, A: 0xff} // rgb(156, 39, 176)
	Purple600       = color.NRGBA{R: 0x8e, G: 0x24, B: 0xaa, A: 0xff} // rgb(142, 36, 170)
	Purple700       = color.NRGBA{R: 0x7b, G: 0x1f, B: 0xa2, A: 0xff} // rgb(123, 31, 162)
	Purple800       = color.NRGBA{R: 0x6a, G: 0x1b, B: 0x9a, A: 0xff} // rgb(106, 27, 154)
	Purple900       = color.NRGBA{R: 0x4a, G: 0x14, B: 0x8c, A: 0xff} // rgb(74, 20, 140)
	PurpleA100      = color.NRGBA{R: 0xea, G: 0x80, B: 0xfc, A: 0xff} // rgb(234, 128, 252)
	PurpleA200      = color.NRGBA{R: 0xe0, G: 0x40, B: 0xfb, A: 0xff} // rgb(224, 64, 251)
	PurpleA400      = color.NRGBA{R: 0xd5, B: 0xf9, A: 0xff}          // rgb(213, 0, 249)
	PurpleA700      = color.NRGBA{R: 0xaa, B: 0xff, A: 0xff}          // rgb(170, 0, 255)
	DeepPurple50    = color.NRGBA{R: 0xed, G: 0xe7, B: 0xf6, A: 0xff} // rgb(237, 231, 246)
	DeepPurple100   = color.NRGBA{R: 0xd1, G: 0xc4, B: 0xe9, A: 0xff} // rgb(209, 196, 233)
	DeepPurple200   = color.NRGBA{R: 0xb3, G: 0x9d, B: 0xdb, A: 0xff} // rgb(179, 157, 219)
	DeepPurple300   = color.NRGBA{R: 0x95, G: 0x75, B: 0xcd, A: 0xff} // rgb(149, 117, 205)
	DeepPurple400   = color.NRGBA{R: 0x7e, G: 0x57, B: 0xc2, A: 0xff} // rgb(126, 87, 194)
	DeepPurple500   = color.NRGBA{R: 0x67, G: 0x3a, B: 0xb7, A: 0xff} // rgb(103, 58, 183)
	DeepPurple600   = color.NRGBA{R: 0x5e, G: 0x35, B: 0xb1, A: 0xff} // rgb(94, 53, 177)
	DeepPurple700   = color.NRGBA{R: 0x51, G: 0x2d, B: 0xa8, A: 0xff} // rgb(81, 45, 168)
	DeepPurple800   = color.NRGBA{R: 0x45, G: 0x27, B: 0xa0, A: 0xff} // rgb(69, 39, 160)
	DeepPurple900   = color.NRGBA{R: 0x31, G: 0x1b, B: 0x92, A: 0xff} // rgb(49, 27, 146)
	DeepPurpleA100  = color.NRGBA{R: 0xb3, G: 0x88, B: 0xff, A: 0xff} // rgb(179, 136, 255)
	DeepPurpleA200  = color.NRGBA{R: 0x7c, G: 0x4d, B: 0xff, A: 0xff} // rgb(124, 77, 255)
	DeepPurpleA400  = color.NRGBA{R: 0x65, G: 0x1f, B: 0xff, A: 0xff} // rgb(101, 31, 255)
	DeepPurpleA700  = color.NRGBA{R: 0x62, B: 0xea, A: 0xff}          // rgb(98, 0, 234)
	Indigo50        = color.NRGBA{R: 0xe8, G: 0xea, B: 0xf6, A: 0xff} // rgb(232, 234, 246)
	Indigo100       = color.NRGBA{R: 0xc5, G: 0xca, B: 0xe9, A: 0xff} // rgb(197, 202, 233)
	Indigo200       = color.NRGBA{R: 0x9f, G: 0xa8, B: 0xda, A: 0xff} // rgb(159, 168, 218)
	Indigo300       = color.NRGBA{R: 0x79, G: 0x86, B: 0xcb, A: 0xff} // rgb(121, 134, 203)
	Indigo400       = color.NRGBA{R: 0x5c, G: 0x6b, B: 0xc0, A: 0xff} // rgb(92, 107, 192)
	Indigo500       = color.NRGBA{R: 0x3f, G: 0x51, B: 0xb5, A: 0xff} // rgb(63, 81, 181)
	Indigo600       = color.NRGBA{R: 0x39, G: 0x49, B: 0xab, A: 0xff} // rgb(57, 73, 171)
	Indigo700       = color.NRGBA{R: 0x30, G: 0x3f, B: 0x9f, A: 0xff} // rgb(48, 63, 159)
	Indigo800       = color.NRGBA{R: 0x28, G: 0x35, B: 0x93, A: 0xff} // rgb(40, 53, 147)
	Indigo900       = color.NRGBA{R: 0x1a, G: 0x23, B: 0x7e, A: 0xff} // rgb(26, 35, 126)
	IndigoA100      = color.NRGBA{R: 0x8c, G: 0x9e, B: 0xff, A: 0xff} // rgb(140, 158, 255)
	IndigoA200      = color.NRGBA{R: 0x53, G: 0x6d, B: 0xfe, A: 0xff} // rgb(83, 109, 254)
	IndigoA400      = color.NRGBA{R: 0x3d, G: 0x5a, B: 0xfe, A: 0xff} // rgb(61, 90, 254)
	IndigoA700      = color.NRGBA{R: 0x30, G: 0x4f, B: 0xfe, A: 0xff} // rgb(48, 79, 254)
	Blue50          = color.NRGBA{R: 0xe3, G: 0xf2, B: 0xfd, A: 0xff} // rgb(227, 242, 253)
	Blue100         = color.NRGBA{R: 0xbb, G: 0xde, B: 0xfb, A: 0xff} // rgb(187, 222, 251)
	Blue200         = color.NRGBA{R: 0x90, G: 0xca, B: 0xf9, A: 0xff} // rgb(144, 202, 249)
	Blue300         = color.NRGBA{R: 0x64, G: 0xb5, B: 0xf6, A: 0xff} // rgb(100, 181, 246)
	Blue400         = color.NRGBA{R: 0x42, G: 0xa5, B: 0xf5, A: 0xff} // rgb(66, 165, 245)
	Blue500         = color.NRGBA{R: 0x21, G: 0x96, B: 0xf3, A: 0xff} // rgb(33, 150, 243)
	Blue600         = color.NRGBA{R: 0x1e, G: 0x88, B: 0xe5, A: 0xff} // rgb(30, 136, 229)
	Blue700         = color.NRGBA{R: 0x19, G: 0x76, B: 0xd2, A: 0xff} // rgb(25, 118, 210)
	Blue800         = color.NRGBA{R: 0x15, G: 0x65, B: 0xc0, A: 0xff} // rgb(21, 101, 192)
	Blue900         = color.NRGBA{R: 0x0d, G: 0x47, B: 0xa1, A: 0xff} // rgb(13, 71, 161)
	BlueA100        = color.NRGBA{R: 0x82, G: 0xb1, B: 0xff, A: 0xff} // rgb(130, 177, 255)
	BlueA200        = color.NRGBA{R: 0x44, G: 0x8a, B: 0xff, A: 0xff} // rgb(68, 138, 255)
	BlueA400        = color.NRGBA{R: 0x29, G: 0x79, B: 0xff, A: 0xff} // rgb(41, 121, 255)
	BlueA700        = color.NRGBA{R: 0x29, G: 0x62, B: 0xff, A: 0xff} // rgb(41, 98, 255)
	LightBlue50     = color.NRGBA{R: 0xe1, G: 0xf5, B: 0xfe, A: 0xff} // rgb(225, 245, 254)
	LightBlue100    = color.NRGBA{R: 0xb3, G: 0xe5, B: 0xfc, A: 0xff} // rgb(179, 229, 252)
	LightBlue200    = color.NRGBA{R: 0x81, G: 0xd4, B: 0xfa, A: 0xff} // rgb(129, 212, 250)
	LightBlue300    = color.NRGBA{R: 0x4f, G: 0xc3, B: 0xf7, A: 0xff} // rgb(79, 195, 247)
	LightBlue400    = color.NRGBA{R: 0x29, G: 0xb6, B: 0xf6, A: 0xff} // rgb(41, 182, 246)
	LightBlue500    = color.NRGBA{R: 0x03, G: 0xa9, B: 0xf4, A: 0xff} // rgb(3, 169, 244)
	LightBlue600    = color.NRGBA{R: 0x03, G: 0x9b, B: 0xe5, A: 0xff} // rgb(3, 155, 229)
	LightBlue700    = color.NRGBA{R: 0x02, G: 0x88, B: 0xd1, A: 0xff} // rgb(2, 136, 209)
	LightBlue800    = color.NRGBA{R: 0x02, G: 0x77, B: 0xbd, A: 0xff} // rgb(2, 119, 189)
	LightBlue900    = color.NRGBA{R: 0x01, G: 0x57, B: 0x9b, A: 0xff} // rgb(1, 87, 155)
	LightBlueA100   = color.NRGBA{R: 0x80, G: 0xd8, B: 0xff, A: 0xff} // rgb(128, 216, 255)
	LightBlueA200   = color.NRGBA{R: 0x40, G: 0xc4, B: 0xff, A: 0xff} // rgb(64, 196, 255)
	LightBlueA400   = color.NRGBA{G: 0xb0, B: 0xff, A: 0xff}          // rgb(0, 176, 255)
	LightBlueA700   = color.NRGBA{G: 0x91, B: 0xea, A: 0xff}          // rgb(0, 145, 234)
	Cyan50          = color.NRGBA{R: 0xe0, G: 0xf7, B: 0xfa, A: 0xff} // rgb(224, 247, 250)
	Cyan100         = color.NRGBA{R: 0xb2, G: 0xeb, B: 0xf2, A: 0xff} // rgb(178, 235, 242)
	Cyan200         = color.NRGBA{R: 0x80, G: 0xde, B: 0xea, A: 0xff} // rgb(128, 222, 234)
	Cyan300         = color.NRGBA{R: 0x4d, G: 0xd0, B: 0xe1, A: 0xff} // rgb(77, 208, 225)
	Cyan400         = color.NRGBA{R: 0x26, G: 0xc6, B: 0xda, A: 0xff} // rgb(38, 198, 218)
	Cyan500         = color.NRGBA{G: 0xbc, B: 0xd4, A: 0xff}          // rgb(0, 188, 212)
	Cyan600         = color.NRGBA{G: 0xac, B: 0xc1, A: 0xff}          // rgb(0, 172, 193)
	Cyan700         = color.NRGBA{G: 0x97, B: 0xa7, A: 0xff}          // rgb(0, 151, 167)
	Cyan800         = color.NRGBA{G: 0x83, B: 0x8f, A: 0xff}          // rgb(0, 131, 143)
	Cyan900         = color.NRGBA{G: 0x60, B: 0x64, A: 0xff}          // rgb(0, 96, 100)
	CyanA100        = color.NRGBA{R: 0x84, G: 0xff, B: 0xff, A: 0xff} // rgb(132, 255, 255)
	CyanA200        = color.NRGBA{R: 0x18, G: 0xff, B: 0xff, A: 0xff} // rgb(24, 255, 255)
	CyanA400        = color.NRGBA{G: 0xe5, B: 0xff, A: 0xff}          // rgb(0, 229, 255)
	CyanA700        = color.NRGBA{G: 0xb8, B: 0xd4, A: 0xff}          // rgb(0, 184, 212)
	Teal50          = color.NRGBA{R: 0xe0, G: 0xf2, B: 0xf1, A: 0xff} // rgb(224, 242, 241)
	Teal100         = color.NRGBA{R: 0xb2, G: 0xdf, B: 0xdb, A: 0xff} // rgb(178, 223, 219)
	Teal200         = color.NRGBA{R: 0x80, G: 0xcb, B: 0xc4, A: 0xff} // rgb(128, 203, 196)
	Teal300         = color.NRGBA{R: 0x4d, G: 0xb6, B: 0xac, A: 0xff} // rgb(77, 182, 172)
	Teal400         = color.NRGBA{R: 0x26, G: 0xa6, B: 0x9a, A: 0xff} // rgb(38, 166, 154)
	Teal500         = color.NRGBA{G: 0x96, B: 0x88, A: 0xff}          // rgb(0, 150, 136)
	Teal600         = color.NRGBA{G: 0x89, B: 0x7b, A: 0xff}          // rgb(0, 137, 123)
	Teal700         = color.NRGBA{G: 0x79, B: 0x6b, A: 0xff}          // rgb(0, 121, 107)
	Teal800         = color.NRGBA{G: 0x69, B: 0x5c, A: 0xff}          // rgb(0, 105, 92)
	Teal900         = color.NRGBA{G: 0x4d, B: 0x40, A: 0xff}          // rgb(0, 77, 64)
	TealA100        = color.NRGBA{R: 0xa7, G: 0xff, B: 0xeb, A: 0xff} // rgb(167, 255, 235)
	TealA200        = color.NRGBA{R: 0x64, G: 0xff, B: 0xda, A: 0xff} // rgb(100, 255, 218)
	TealA400        = color.NRGBA{R: 0x1d, G: 0xe9, B: 0xb6, A: 0xff} // rgb(29, 233, 182)
	TealA700        = color.NRGBA{G: 0xbf, B: 0xa5, A: 0xff}          // rgb(0, 191, 165)
	Green50         = color.NRGBA{R: 0xe8, G: 0xf5, B: 0xe9, A: 0xff} // rgb(232, 245, 233)
	Green100        = color.NRGBA{R: 0xc8, G: 0xe6, B: 0xc9, A: 0xff} // rgb(200, 230, 201)
	Green200        = color.NRGBA{R: 0xa5, G: 0xd6, B: 0xa7, A: 0xff} // rgb(165, 214, 167)
	Green300        = color.NRGBA{R: 0x81, G: 0xc7, B: 0x84, A: 0xff} // rgb(129, 199, 132)
	Green400        = color.NRGBA{R: 0x66, G: 0xbb, B: 0x6a, A: 0xff} // rgb(102, 187, 106)
	Green500        = color.NRGBA{R: 0x4c, G: 0xaf, B: 0x50, A: 0xff} // rgb(76, 175, 80)
	Green600        = color.NRGBA{R: 0x43, G: 0xa0, B: 0x47, A: 0xff} // rgb(67, 160, 71)
	Green700        = color.NRGBA{R: 0x38, G: 0x8e, B: 0x3c, A: 0xff} // rgb(56, 142, 60)
	Green800        = color.NRGBA{R: 0x2e, G: 0x7d, B: 0x32, A: 0xff} // rgb(46, 125, 50)
	Green900        = color.NRGBA{R: 0x1b, G: 0x5e, B: 0x20, A: 0xff} // rgb(27, 94, 32)
	GreenA100       = color.NRGBA{R: 0xb9, G: 0xf6, B: 0xca, A: 0xff} // rgb(185, 246, 202)
	GreenA200       = color.NRGBA{R: 0x69, G: 0xf0, B: 0xae, A: 0xff} // rgb(105, 240, 174)
	GreenA400       = color.NRGBA{G: 0xe6, B: 0x76, A: 0xff}          // rgb(0, 230, 118)
	GreenA700       = color.NRGBA{G: 0xc8, B: 0x53, A: 0xff}          // rgb(0, 200, 83)
	LightGreen50    = color.NRGBA{R: 0xf1, G: 0xf8, B: 0xe9, A: 0xff} // rgb(241, 248, 233)
	LightGreen100   = color.NRGBA{R: 0xdc, G: 0xed, B: 0xc8, A: 0xff} // rgb(220, 237, 200)
	LightGreen200   = color.NRGBA{R: 0xc5, G: 0xe1, B: 0xa5, A: 0xff} // rgb(197, 225, 165)
	LightGreen300   = color.NRGBA{R: 0xae, G: 0xd5, B: 0x81, A: 0xff} // rgb(174, 213, 129)
	LightGreen400   = color.NRGBA{R: 0x9c, G: 0xcc, B: 0x65, A: 0xff} // rgb(156, 204, 101)
	LightGreen500   = color.NRGBA{R: 0x8b, G: 0xc3, B: 0x4a, A: 0xff} // rgb(139, 195, 74)
	LightGreen600   = color.NRGBA{R: 0x7c, G: 0xb3, B: 0x42, A: 0xff} // rgb(124, 179, 66)
	LightGreen700   = color.NRGBA{R: 0x68, G: 0x9f, B: 0x38, A: 0xff} // rgb(104, 159, 56)
	LightGreen800   = color.NRGBA{R: 0x55, G: 0x8b, B: 0x2f, A: 0xff} // rgb(85, 139, 47)
	LightGreen900   = color.NRGBA{R: 0x33, G: 0x69, B: 0x1e, A: 0xff} // rgb(51, 105, 30)
	LightGreenA100  = color.NRGBA{R: 0xcc, G: 0xff, B: 0x90, A: 0xff} // rgb(204, 255, 144)
	LightGreenA200  = color.NRGBA{R: 0xb2, G: 0xff, B: 0x59, A: 0xff} // rgb(178, 255, 89)
	LightGreenA400  = color.NRGBA{R: 0x76, G: 0xff, B: 0x03, A: 0xff} // rgb(118, 255, 3)
	LightGreenA700  = color.NRGBA{R: 0x64, G: 0xdd, B: 0x17, A: 0xff} // rgb(100, 221, 23)
	Lime50          = color.NRGBA{R: 0xf9, G: 0xfb, B: 0xe7, A: 0xff} // rgb(249, 251, 231)
	Lime100         = color.NRGBA{R: 0xf0, G: 0xf4, B: 0xc3, A: 0xff} // rgb(240, 244, 195)
	Lime200         = color.NRGBA{R: 0xe6, G: 0xee, B: 0x9c, A: 0xff} // rgb(230, 238, 156)
	Lime300         = color.NRGBA{R: 0xdc, G: 0xe7, B: 0x75, A: 0xff} // rgb(220, 231, 117)
	Lime400         = color.NRGBA{R: 0xd4, G: 0xe1, B: 0x57, A: 0xff} // rgb(212, 225, 87)
	Lime500         = color.NRGBA{R: 0xcd, G: 0xdc, B: 0x39, A: 0xff} // rgb(205, 220, 57)
	Lime600         = color.NRGBA{R: 0xc0, G: 0xca, B: 0x33, A: 0xff} // rgb(192, 202, 51)
	Lime700         = color.NRGBA{R: 0xaf, G: 0xb4, B: 0x2b, A: 0xff} // rgb(175, 180, 43)
	Lime800         = color.NRGBA{R: 0x9e, G: 0x9d, B: 0x24, A: 0xff} // rgb(158, 157, 36)
	Lime900         = color.NRGBA{R: 0x82, G: 0x77, B: 0x17, A: 0xff} // rgb(130, 119, 23)
	LimeA100        = color.NRGBA{R: 0xf4, G: 0xff, B: 0x81, A: 0xff} // rgb(244, 255, 129)
	LimeA200        = color.NRGBA{R: 0xee, G: 0xff, B: 0x41, A: 0xff} // rgb(238, 255, 65)
	LimeA400        = color.NRGBA{R: 0xc6, G: 0xff, A: 0xff}          // rgb(198, 255, 0)
	LimeA700        = color.NRGBA{R: 0xae, G: 0xea, A: 0xff}          // rgb(174, 234, 0)
	Yellow50        = color.NRGBA{R: 0xff, G: 0xfd, B: 0xe7, A: 0xff} // rgb(255, 253, 231)
	Yellow100       = color.NRGBA{R: 0xff, G: 0xf9, B: 0xc4, A: 0xff} // rgb(255, 249, 196)
	Yellow200       = color.NRGBA{R: 0xff, G: 0xf5, B: 0x9d, A: 0xff} // rgb(255, 245, 157)
	Yellow300       = color.NRGBA{R: 0xff, G: 0xf1, B: 0x76, A: 0xff} // rgb(255, 241, 118)
	Yellow400       = color.NRGBA{R: 0xff, G: 0xee, B: 0x58, A: 0xff} // rgb(255, 238, 88)
	Yellow500       = color.NRGBA{R: 0xff, G: 0xeb, B: 0x3b, A: 0xff} // rgb(255, 235, 59)
	Yellow600       = color.NRGBA{R: 0xfd, G: 0xd8, B: 0x35, A: 0xff} // rgb(253, 216, 53)
	Yellow700       = color.NRGBA{R: 0xfb, G: 0xc0, B: 0x2d, A: 0xff} // rgb(251, 192, 45)
	Yellow800       = color.NRGBA{R: 0xf9, G: 0xa8, B: 0x25, A: 0xff} // rgb(249, 168, 37)
	Yellow900       = color.NRGBA{R: 0xf5, G: 0x7f, B: 0x17, A: 0xff} // rgb(245, 127, 23)
	YellowA100      = color.NRGBA{R: 0xff, G: 0xff, B: 0x8d, A: 0xff} // rgb(255, 255, 141)
	YellowA200      = color.NRGBA{R: 0xff, G: 0xff, A: 0xff}          // rgb(255, 255, 0)
	YellowA400      = color.NRGBA{R: 0xff, G: 0xea, A: 0xff}          // rgb(255, 234, 0)
	YellowA700      = color.NRGBA{R: 0xff, G: 0xd6, A: 0xff}          // rgb(255, 214, 0)
	Amber50         = color.NRGBA{R: 0xff, G: 0xf8, B: 0xe1, A: 0xff} // rgb(255, 248, 225)
	Amber100        = color.NRGBA{R: 0xff, G: 0xec, B: 0xb3, A: 0xff} // rgb(255, 236, 179)
	Amber200        = color.NRGBA{R: 0xff, G: 0xe0, B: 0x82, A: 0xff} // rgb(255, 224, 130)
	Amber300        = color.NRGBA{R: 0xff, G: 0xd5, B: 0x4f, A: 0xff} // rgb(255, 213, 79)
	Amber400        = color.NRGBA{R: 0xff, G: 0xca, B: 0x28, A: 0xff} // rgb(255, 202, 40)
	Amber500        = color.NRGBA{R: 0xff, G: 0xc1, B: 0x07, A: 0xff} // rgb(255, 193, 7)
	Amber600        = color.NRGBA{R: 0xff, G: 0xb3, A: 0xff}          // rgb(255, 179, 0)
	Amber700        = color.NRGBA{R: 0xff, G: 0xa0, A: 0xff}          // rgb(255, 160, 0)
	Amber800        = color.NRGBA{R: 0xff, G: 0x8f, A: 0xff}          // rgb(255, 143, 0)
	Amber900        = color.NRGBA{R: 0xff, G: 0x6f, A: 0xff}          // rgb(255, 111, 0)
	AmberA100       = color.NRGBA{R: 0xff, G: 0xe5, B: 0x7f, A: 0xff} // rgb(255, 229, 127)
	AmberA200       = color.NRGBA{R: 0xff, G: 0xd7, B: 0x40, A: 0xff} // rgb(255, 215, 64)
	AmberA400       = color.NRGBA{R: 0xff, G: 0xc4, A: 0xff}          // rgb(255, 196, 0)
	AmberA700       = color.NRGBA{R: 0xff, G: 0xab, A: 0xff}          // rgb(255, 171, 0)
	Orange50        = color.NRGBA{R: 0xff, G: 0xf3, B: 0xe0, A: 0xff} // rgb(255, 243, 224)
	Orange100       = color.NRGBA{R: 0xff, G: 0xe0, B: 0xb2, A: 0xff} // rgb(255, 224, 178)
	Orange200       = color.NRGBA{R: 0xff, G: 0xcc, B: 0x80, A: 0xff} // rgb(255, 204, 128)
	Orange300       = color.NRGBA{R: 0xff, G: 0xb7, B: 0x4d, A: 0xff} // rgb(255, 183, 77)
	Orange400       = color.NRGBA{R: 0xff, G: 0xa7, B: 0x26, A: 0xff} // rgb(255, 167, 38)
	Orange500       = color.NRGBA{R: 0xff, G: 0x98, A: 0xff}          // rgb(255, 152, 0)
	Orange600       = color.NRGBA{R: 0xfb, G: 0x8c, A: 0xff}          // rgb(251, 140, 0)
	Orange700       = color.NRGBA{R: 0xf5, G: 0x7c, A: 0xff}          // rgb(245, 124, 0)
	Orange800       = color.NRGBA{R: 0xef, G: 0x6c, A: 0xff}          // rgb(239, 108, 0)
	Orange900       = color.NRGBA{R: 0xe6, G: 0x51, A: 0xff}          // rgb(230, 81, 0)
	OrangeA100      = color.NRGBA{R: 0xff, G: 0xd1, B: 0x80, A: 0xff} // rgb(255, 209, 128)
	OrangeA200      = color.NRGBA{R: 0xff, G: 0xab, B: 0x40, A: 0xff} // rgb(255, 171, 64)
	OrangeA400      = color.NRGBA{R: 0xff, G: 0x91, A: 0xff}          // rgb(255, 145, 0)
	OrangeA700      = color.NRGBA{R: 0xff, G: 0x6d, A: 0xff}          // rgb(255, 109, 0)
	DeepOrange50    = color.NRGBA{R: 0xfb, G: 0xe9, B: 0xe7, A: 0xff} // rgb(251, 233, 231)
	DeepOrange100   = color.NRGBA{R: 0xff, G: 0xcc, B: 0xbc, A: 0xff} // rgb(255, 204, 188)
	DeepOrange200   = color.NRGBA{R: 0xff, G: 0xab, B: 0x91, A: 0xff} // rgb(255, 171, 145)
	DeepOrange300   = color.NRGBA{R: 0xff, G: 0x8a, B: 0x65, A: 0xff} // rgb(255, 138, 101)
	DeepOrange400   = color.NRGBA{R: 0xff, G: 0x70, B: 0x43, A: 0xff} // rgb(255, 112, 67)
	DeepOrange500   = color.NRGBA{R: 0xff, G: 0x57, B: 0x22, A: 0xff} // rgb(255, 87, 34)
	DeepOrange600   = color.NRGBA{R: 0xf4, G: 0x51, B: 0x1e, A: 0xff} // rgb(244, 81, 30)
	DeepOrange700   = color.NRGBA{R: 0xe6, G: 0x4a, B: 0x19, A: 0xff} // rgb(230, 74, 25)
	DeepOrange800   = color.NRGBA{R: 0xd8, G: 0x43, B: 0x15, A: 0xff} // rgb(216, 67, 21)
	DeepOrange900   = color.NRGBA{R: 0xbf, G: 0x36, B: 0x0c, A: 0xff} // rgb(191, 54, 12)
	DeepOrangeA100  = color.NRGBA{R: 0xff, G: 0x9e, B: 0x80, A: 0xff} // rgb(255, 158, 128)
	DeepOrangeA200  = color.NRGBA{R: 0xff, G: 0x6e, B: 0x40, A: 0xff} // rgb(255, 110, 64)
	DeepOrangeA400  = color.NRGBA{R: 0xff, G: 0x3d, A: 0xff}          // rgb(255, 61, 0)
	DeepOrangeA700  = color.NRGBA{R: 0xdd, G: 0x2c, A: 0xff}          // rgb(221, 44, 0)
	Brown50         = color.NRGBA{R: 0xef, G: 0xeb, B: 0xe9, A: 0xff} // rgb(239, 235, 233)
	Brown100        = color.NRGBA{R: 0xd7, G: 0xcc, B: 0xc8, A: 0xff} // rgb(215, 204, 200)
	Brown200        = color.NRGBA{R: 0xbc, G: 0xaa, B: 0xa4, A: 0xff} // rgb(188, 170, 164)
	Brown300        = color.NRGBA{R: 0xa1, G: 0x88, B: 0x7f, A: 0xff} // rgb(161, 136, 127)
	Brown400        = color.NRGBA{R: 0x8d, G: 0x6e, B: 0x63, A: 0xff} // rgb(141, 110, 99)
	Brown500        = color.NRGBA{R: 0x79, G: 0x55, B: 0x48, A: 0xff} // rgb(121, 85, 72)
	Brown600        = color.NRGBA{R: 0x6d, G: 0x4c, B: 0x41, A: 0xff} // rgb(109, 76, 65)
	Brown700        = color.NRGBA{R: 0x5d, G: 0x40, B: 0x37, A: 0xff} // rgb(93, 64, 55)
	Brown800        = color.NRGBA{R: 0x4e, G: 0x34, B: 0x2e, A: 0xff} // rgb(78, 52, 46)
	Brown900        = color.NRGBA{R: 0x3e, G: 0x27, B: 0x23, A: 0xff} // rgb(62, 39, 35)
	Grey50          = color.NRGBA{R: 0xfa, G: 0xfa, B: 0xfa, A: 0xff} // rgb(250, 250, 250)
	Grey100         = color.NRGBA{R: 0xf5, G: 0xf5, B: 0xf5, A: 0xff} // rgb(245, 245, 245)
	Grey200         = color.NRGBA{R: 0xee, G: 0xee, B: 0xee, A: 0xff} // rgb(238, 238, 238)
	Grey300         = color.NRGBA{R: 0xe0, G: 0xe0, B: 0xe0, A: 0xff} // rgb(224, 224, 224)
	Grey400         = color.NRGBA{R: 0xbd, G: 0xbd, B: 0xbd, A: 0xff} // rgb(189, 189, 189)
	Grey500         = color.NRGBA{R: 0x9e, G: 0x9e, B: 0x9e, A: 0xff} // rgb(158, 158, 158)
	Grey600         = color.NRGBA{R: 0x75, G: 0x75, B: 0x75, A: 0xff} // rgb(117, 117, 117)
	Grey700         = color.NRGBA{R: 0x61, G: 0x61, B: 0x61, A: 0xff} // rgb(97, 97, 97)
	Grey800         = color.NRGBA{R: 0x42, G: 0x42, B: 0x42, A: 0xff} // rgb(66, 66, 66)
	Grey900         = color.NRGBA{R: 0x21, G: 0x21, B: 0x21, A: 0xff} // rgb(33, 33, 33)
	BlueGrey50      = color.NRGBA{R: 0xec, G: 0xef, B: 0xf1, A: 0xff} // rgb(236, 239, 241)
	BlueGrey100     = color.NRGBA{R: 0xcf, G: 0xd8, B: 0xdc, A: 0xff} // rgb(207, 216, 220)
	BlueGrey200     = color.NRGBA{R: 0xb0, G: 0xbe, B: 0xc5, A: 0xff} // rgb(176, 190, 197)
	BlueGrey300     = color.NRGBA{R: 0x90, G: 0xa4, B: 0xae, A: 0xff} // rgb(144, 164, 174)
	BlueGrey400     = color.NRGBA{R: 0x78, G: 0x90, B: 0x9c, A: 0xff} // rgb(120, 144, 156)
	BlueGrey500     = color.NRGBA{R: 0x60, G: 0x7d, B: 0x8b, A: 0xff} // rgb(96, 125, 139)
	BlueGrey600     = color.NRGBA{R: 0x54, G: 0x6e, B: 0x7a, A: 0xff} // rgb(84, 110, 122)
	BlueGrey700     = color.NRGBA{R: 0x45, G: 0x5a, B: 0x64, A: 0xff} // rgb(69, 90, 100)
	BlueGrey800     = color.NRGBA{R: 0x37, G: 0x47, B: 0x4f, A: 0xff} // rgb(55, 71, 79)
	BlueGrey900     = color.NRGBA{R: 0x26, G: 0x32, B: 0x38, A: 0xff} // rgb(38, 50, 56)
	Black           = color.NRGBA{A: 0xff}                            // rgb(0, 0, 0)
	White           = color.NRGBA{R: 0xff, G: 0xff, B: 0xff, A: 0xff} // rgb(255, 255, 255)
	DividerFg       = color.NRGBA{R: 88, G: 88, B: 88, A: 255}
	BackgroundColor = color.NRGBA{R: 54, G: 54, B: 54, A: 255}
	ColorPink       = color.NRGBA{R: 166, G: 96, B: 192, A: 255}
	ColorHeaderFg   = color.NRGBA{R: 76, G: 76, B: 76, A: 255}
)
