package images

import (
	"embed"
	"strings"

	"github.com/ddkwork/golibrary/std/stream"
)

func svgCallback(value []byte) []byte {
	if strings.Contains(string(value), "fill=\"none\"") {
		// return []byte(strings.Replace(string(value), "fill=\"none\"", "fill=\"white\"", 1))
	}
	return []byte(strings.Replace(string(value), "<path", "<path fill=\"white\"", 1))
}

// 取色
// https://products.eptimize.app/zh/color-convert/rgb-to-rgba
//
//go:embed images/*.svg
var svgFs embed.FS

var (
	svgEmbedFileMap                = stream.ReadEmbedFileMap(svgFs, "images")
	SvgIconBookmark                = svgEmbedFileMap.GetMustCallback("Bookmark.svg", svgCallback)
	SvgIconCircledChevronDown      = svgEmbedFileMap.GetMustCallback("CircledChevronDown.svg", svgCallback)
	SvgIconConvertToNonContainer   = svgEmbedFileMap.GetMustCallback("ConvertToNonContainer.svg", svgCallback)
	SvgIconConvertToContainer      = svgEmbedFileMap.GetMustCallback("ConvertTo_Container.svg", svgCallback)
	SvgIconLightning               = svgEmbedFileMap.GetMustCallback("Lightning.svg", svgCallback)
	SvgIconLogout                  = svgEmbedFileMap.GetMustCallback("Logout.svg", svgCallback)
	SvgIconMoon                    = svgEmbedFileMap.GetMustCallback("Moon.svg", svgCallback)
	SvgIconSun                     = svgEmbedFileMap.GetMustCallback("Sun.svg", svgCallback)
	SvgIconWarning                 = svgEmbedFileMap.GetMustCallback("Warning.svg", svgCallback)
	SvgIconAddComment              = svgEmbedFileMap.GetMustCallback("add_comment.svg", svgCallback)
	SvgIconAttributes              = svgEmbedFileMap.GetMustCallback("attributes.svg", svgCallback)
	SvgIconBack                    = svgEmbedFileMap.GetMustCallback("back.svg", svgCallback)
	SvgIconBodyType                = svgEmbedFileMap.GetMustCallback("body_type.svg", svgCallback)
	SvgIconBrokenImage             = svgEmbedFileMap.GetMustCallback("broken_image.svg", svgCallback)
	SvgIconCalculator              = svgEmbedFileMap.GetMustCallback("calculator.svg", svgCallback)
	SvgIconCheckmark               = svgEmbedFileMap.GetMustCallback("checkmark.svg", svgCallback)
	SvgIconChevronRight            = svgEmbedFileMap.GetMustCallback("chevron_right.svg", svgCallback)
	SvgIconCircledAdd              = svgEmbedFileMap.GetMustCallback("circled_add.svg", svgCallback)
	SvgIconCircledChevronRight     = svgEmbedFileMap.GetMustCallback("circled_chevron_right.svg", svgCallback)
	SvgIconCircledExclamation      = svgEmbedFileMap.GetMustCallback("circled_exclamation.svg", svgCallback)
	SvgIconCircledQuestion         = svgEmbedFileMap.GetMustCallback("circled_question.svg", svgCallback)
	SvgIconCircledVerticalEllipsis = svgEmbedFileMap.GetMustCallback("circled_vertical_ellipsis.svg", svgCallback)
	SvgIconCircledX                = svgEmbedFileMap.GetMustCallback("circled_x.svg", svgCallback)
	SvgIconClone                   = svgEmbedFileMap.GetMustCallback("clone.svg", svgCallback)
	SvgIconClosedFolder            = svgEmbedFileMap.GetMustCallback("closed_folder.svg", svgCallback)
	SvgIconCoins                   = svgEmbedFileMap.GetMustCallback("coins.svg", svgCallback)
	SvgIconContentPasteTwotone     = svgEmbedFileMap.GetMustCallback("content_paste_twotone.svg", svgCallback)
	SvgIconCopy                    = svgEmbedFileMap.GetMustCallback("copy.svg", svgCallback)
	SvgIconDash                    = svgEmbedFileMap.GetMustCallback("dash.svg", svgCallback)
	SvgIconDatabase                = svgEmbedFileMap.GetMustCallback("database.svg", svgCallback)
	SvgIconDocument                = svgEmbedFileMap.GetMustCallback("document.svg", svgCallback)
	SvgIconDownToBracket           = svgEmbedFileMap.GetMustCallback("down_to_bracket.svg", svgCallback)
	SvgIconDownload                = svgEmbedFileMap.GetMustCallback("download.svg", svgCallback)
	SvgIconDuplicate               = svgEmbedFileMap.GetMustCallback("duplicate.svg", svgCallback)
	SvgIconEdit                    = svgEmbedFileMap.GetMustCallback("edit.svg", svgCallback)
	SvgIconFirst                   = svgEmbedFileMap.GetMustCallback("first.svg", svgCallback)
	SvgIconFirstAidKit             = svgEmbedFileMap.GetMustCallback("first_aid_kit.svg", svgCallback)
	SvgIconFolderSpecialTwotone    = svgEmbedFileMap.GetMustCallback("folder_special_twotone.svg", svgCallback)
	SvgIconForward                 = svgEmbedFileMap.GetMustCallback("forward.svg", svgCallback)
	SvgIconGcsCampaign             = svgEmbedFileMap.GetMustCallback("gcs_campaign.svg", svgCallback)
	SvgIconGcsEquipment            = svgEmbedFileMap.GetMustCallback("gcs_equipment.svg", svgCallback)
	SvgIconGcsEquipmentModifiers   = svgEmbedFileMap.GetMustCallback("gcs_equipment_modifiers.svg", svgCallback)
	SvgIconGcsLoot                 = svgEmbedFileMap.GetMustCallback("gcs_loot.svg", svgCallback)
	SvgIconGcsNotes                = svgEmbedFileMap.GetMustCallback("gcs_notes.svg", svgCallback)
	SvgIconGcsSheet                = svgEmbedFileMap.GetMustCallback("gcs_sheet.svg", svgCallback)
	SvgIconGcsSkills               = svgEmbedFileMap.GetMustCallback("gcs_skills.svg", svgCallback)
	SvgIconGcsSpells               = svgEmbedFileMap.GetMustCallback("gcs_spells.svg", svgCallback)
	SvgIconGcsTemplate             = svgEmbedFileMap.GetMustCallback("gcs_template.svg", svgCallback)
	SvgIconGcsTraitModifiers       = svgEmbedFileMap.GetMustCallback("gcs_trait_modifiers.svg", svgCallback)
	SvgIconGcsTraits               = svgEmbedFileMap.GetMustCallback("gcs_traits.svg", svgCallback)
	SvgIconGears                   = svgEmbedFileMap.GetMustCallback("gears.svg", svgCallback)
	SvgIconGenericFile             = svgEmbedFileMap.GetMustCallback("generic_file.svg", svgCallback)
	SvgIconGrip                    = svgEmbedFileMap.GetMustCallback("grip.svg", svgCallback)
	SvgIconHelp                    = svgEmbedFileMap.GetMustCallback("help.svg", svgCallback)
	SvgIconHierarchy               = svgEmbedFileMap.GetMustCallback("hierarchy.svg", svgCallback)
	SvgIconImageFile               = svgEmbedFileMap.GetMustCallback("image_file.svg", svgCallback)
	SvgIconInfo                    = svgEmbedFileMap.GetMustCallback("info.svg", svgCallback)
	SvgIconLast                    = svgEmbedFileMap.GetMustCallback("last.svg", svgCallback)
	SvgIconLink                    = svgEmbedFileMap.GetMustCallback("link.svg", svgCallback)
	SvgIconMarkdownFile            = svgEmbedFileMap.GetMustCallback("markdown_file.svg", svgCallback)
	SvgIconMediation               = svgEmbedFileMap.GetMustCallback("mediation.svg", svgCallback)
	SvgIconMeleeWeapon             = svgEmbedFileMap.GetMustCallback("melee_weapon.svg", svgCallback)
	SvgIconMenu                    = svgEmbedFileMap.GetMustCallback("menu.svg", svgCallback)
	SvgIconNaming                  = svgEmbedFileMap.GetMustCallback("naming.svg", svgCallback)
	SvgIconNewFolder               = svgEmbedFileMap.GetMustCallback("new_folder.svg", svgCallback)
	SvgIconNext                    = svgEmbedFileMap.GetMustCallback("next.svg", svgCallback)
	SvgIconNot                     = svgEmbedFileMap.GetMustCallback("not.svg", svgCallback)
	SvgIconNotesCollapse           = svgEmbedFileMap.GetMustCallback("notes-collapse.svg", svgCallback)
	SvgIconNotesExpand             = svgEmbedFileMap.GetMustCallback("notes-expand.svg", svgCallback)
	SvgIconOpenFolder              = svgEmbedFileMap.GetMustCallback("open_folder.svg", svgCallback)
	SvgIconPdfFile                 = svgEmbedFileMap.GetMustCallback("pdf_file.svg", svgCallback)
	SvgIconPolylineRound           = svgEmbedFileMap.GetMustCallback("polyline_round.svg", svgCallback)
	SvgIconPrevious                = svgEmbedFileMap.GetMustCallback("previous.svg", svgCallback)
	SvgIconRandomize               = svgEmbedFileMap.GetMustCallback("randomize.svg", svgCallback)
	SvgIconRangedWeapon            = svgEmbedFileMap.GetMustCallback("ranged_weapon.svg", svgCallback)
	SvgIconReleaseNotes            = svgEmbedFileMap.GetMustCallback("release_notes.svg", svgCallback)
	SvgIconReset                   = svgEmbedFileMap.GetMustCallback("reset.svg", svgCallback)
	SvgIconSaveContent             = svgEmbedFileMap.GetMustCallback("save_content.svg", svgCallback)
	SvgIconSettings                = svgEmbedFileMap.GetMustCallback("settings.svg", svgCallback)
	SvgIconSideBar                 = svgEmbedFileMap.GetMustCallback("side_bar.svg", svgCallback)
	SvgIconSignPost                = svgEmbedFileMap.GetMustCallback("sign_post.svg", svgCallback)
	SvgIconSizeToFit               = svgEmbedFileMap.GetMustCallback("size_to_fit.svg", svgCallback)
	SvgIconSortAscending           = svgEmbedFileMap.GetMustCallback("sort_ascending.svg", svgCallback)
	SvgIconSortDescending          = svgEmbedFileMap.GetMustCallback("sort_descending.svg", svgCallback)
	SvgIconStack                   = svgEmbedFileMap.GetMustCallback("stack.svg", svgCallback)
	SvgIconStamper                 = svgEmbedFileMap.GetMustCallback("stamper.svg", svgCallback)
	SvgIconStar                    = svgEmbedFileMap.GetMustCallback("star.svg", svgCallback)
	SvgIconTrash                   = svgEmbedFileMap.GetMustCallback("trash.svg", svgCallback)
	SvgIconTriangleExclamation     = svgEmbedFileMap.GetMustCallback("triangle_exclamation.svg", svgCallback)
	SvgIconWeight                  = svgEmbedFileMap.GetMustCallback("weight.svg", svgCallback)
	SvgIconWindowMaximize          = svgEmbedFileMap.GetMustCallback("window_maximize.svg", svgCallback)
	SvgIconWindowRestore           = svgEmbedFileMap.GetMustCallback("window_restore.svg", svgCallback)
)
