package main

import (
	"fmt"
	"time"
	//"github.com/ddkwork/app/widget"
	//"github.com/ddkwork/golibrary/mylog"
	//"github.com/ddkwork/unison"
	//"github.com/ddkwork/unison/app"
)

var info = ""

func main() {
	app.Run("计件表", func(w *unison.Window) {
		w.Content().AddChild(layout())
		w.SetTitle(w.Title() + info)
	})
}

func layout() unison.Paneler {
	return widget.NewTableScroll(ManPieceworkEditData{}, widget.TableContext[ManPieceworkEditData]{
		ContextMenuItems: nil,
		MarshalRow: func(node *widget.Node[ManPieceworkEditData]) (cells []widget.CellData) {
			timeFmt := node.Data.Time.Format("2006-01-02")
			NumberOfCompleteVehiclesSum := node.Data.NumberOfCompleteVehiclesSum()
			FoamBoxSum := node.Data.FoamBoxSum()
			PlasticFrameSum := node.Data.PlasticFrameSum()
			Mark1 := node.Data.Mark1
			Mark1Bar := node.Data.Mark1Bar
			Mark2 := node.Data.Mark2
			Mark3 := node.Data.Mark3
			Level3 := node.Data.Level3
			Supermarket3Labels := node.Data.Supermarket3Labels
			SmallFruit := node.Data.SmallFruit
			BigFruit := node.Data.BigFruit
			FlowersFruits := node.Data.FlowersFruits
			SmallFruitMark1 := node.Data.SmallFruitMark1

			Mark1_J := node.Data.Mark1_J
			Mark2_J := node.Data.Mark2_J
			Mark3_J := node.Data.Mark3_J
			SmallBunchFruits := node.Data.SmallBunchFruits
			BunchFruits := node.Data.BunchFruits
			FineBunchFruits := node.Data.FineBunchFruits
			SweetBunchFruits := node.Data.SweetBunchFruits
			BunchFruitsAA := node.Data.BunchFruitsAA
			AAA := node.Data.AAA
			TurnoverBasket := node.Data.TurnoverBasket
			ElectronicCommerce := node.Data.ElectronicCommerce
			Carpooling := node.Data.Carpooling

			if node.Container() {
				timeFmt = node.Sum()
				node.Walk(func(node *widget.Node[ManPieceworkEditData]) {
					FoamBoxSum += node.Data.FoamBoxSum()
					PlasticFrameSum += node.Data.PlasticFrameSum()
					NumberOfCompleteVehiclesSum += node.Data.NumberOfCompleteVehiclesSum()
					Mark1 += node.Data.Mark1
					Mark1Bar += node.Data.Mark1Bar
					Mark2 += node.Data.Mark2
					Mark3 += node.Data.Mark3
					Level3 += node.Data.Level3
					Supermarket3Labels += node.Data.Supermarket3Labels
					SmallFruit += node.Data.SmallFruit
					BigFruit += node.Data.BigFruit
					FlowersFruits += node.Data.FlowersFruits
					SmallFruitMark1 += node.Data.SmallFruitMark1

					Mark1_J += node.Data.Mark1_J
					Mark2_J += node.Data.Mark2_J
					Mark3_J += node.Data.Mark3_J
					SmallBunchFruits += node.Data.SmallBunchFruits
					BunchFruits += node.Data.BunchFruits
					FineBunchFruits += node.Data.FineBunchFruits
					SweetBunchFruits += node.Data.SweetBunchFruits
					BunchFruitsAA += node.Data.BunchFruitsAA
					AAA += node.Data.AAA
					TurnoverBasket += node.Data.TurnoverBasket
					ElectronicCommerce += node.Data.ElectronicCommerce
					Carpooling += node.Data.Carpooling
				})
			}
			return []widget.CellData{
				{Text: timeFmt},
				{Text: node.Data.Destination},
				{Text: fmt.Sprint(NumberOfCompleteVehiclesSum), FgColor: unison.Red},
				{Text: fmt.Sprint(FoamBoxSum), FgColor: unison.Pink},
				{Text: fmt.Sprint(PlasticFrameSum), FgColor: unison.Green},
				{Text: fmt.Sprint(Mark1)},
				{Text: fmt.Sprint(Mark1Bar)},
				{Text: fmt.Sprint(Mark2)},
				{Text: fmt.Sprint(Mark3)},
				{Text: fmt.Sprint(Level3)},
				{Text: fmt.Sprint(Supermarket3Labels)},
				{Text: fmt.Sprint(SmallFruit)},
				{Text: fmt.Sprint(BigFruit)},
				{Text: fmt.Sprint(FlowersFruits)},

				{Text: fmt.Sprint(SmallFruitMark1), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(Mark1_J), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(Mark2_J), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(Mark3_J), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(SmallBunchFruits), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(BunchFruits), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(FineBunchFruits), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(SweetBunchFruits), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(BunchFruitsAA), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(AAA), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(TurnoverBasket), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(ElectronicCommerce), FgColor: unison.YellowGreen},
				{Text: fmt.Sprint(Carpooling), FgColor: unison.Tomato},
				{Text: node.Data.Note},
			}
		},
		UnmarshalRow: func(node *widget.Node[ManPieceworkEditData], values []string) {
			node.Data = ManPieceworkEditData{
				Time: time.Time{},
				Note: "",
			}
		},
		SelectionChangedCallback: func(root *widget.Node[ManPieceworkEditData]) {
		},
		SetRootRowsCallBack: func(root *widget.Node[ManPieceworkEditData]) {
			all := widget.NewContainerNode("2022-02-05", ManPieceworkEditData{
				Time: mylog.Check2(time.Parse("2006-01-02", "2022-02-05")),
			})
			root.AddChild(all)
			fnWageDay := func(date string, wuhan, chengdu, erMei ManPieceworkEditData) {
				containerWageDay := widget.NewContainerNode(date, ManPieceworkEditData{
					Time: mylog.Check2(time.Parse("2006-01-02", date)),
				})
				all.AddChild(containerWageDay)
				wuhan.Destination = "武汉"
				chengdu.Destination = "成都"
				erMei.Destination = "峨眉"
				wuhan.Time = containerWageDay.Data.Time
				chengdu.Time = containerWageDay.Data.Time
				erMei.Time = containerWageDay.Data.Time

				if wuhan.NumberOfCompleteVehiclesSum() > 0 {
					containerWageDay.AddChildByData(wuhan)
				}
				if chengdu.NumberOfCompleteVehiclesSum() > 0 {
					containerWageDay.AddChildByData(chengdu)
				}
				if erMei.NumberOfCompleteVehiclesSum() > 0 {
					containerWageDay.AddChildByData(erMei)
				}
				if containerWageDay.LenChildren() == 0 {
					containerWageDay.Data.Note = "没发车"
				}
				if containerWageDay.LenChildren() == 1 {
					data := containerWageDay.Children[0].Data
					containerWageDay.RemoveFromParent()
					all.AddChildByData(data)
				}
			}
			fnWageDay("2022-02-05", ManPieceworkEditData{}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    0,
				Level3:                   0,
				Supermarket3Labels:       497,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-06", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-02-07", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    503,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-02-08", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    0,
				Level3:                   503,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    0,
				Level3:                   0,
				Supermarket3Labels:       289,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  80,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-09", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    503,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-02-10", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    503,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-02-11", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    503,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    0,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          53,
				Mark1_J:                  80,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-12", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    507,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    0,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  41,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         22,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-13", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-02-14", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    507,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    0,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  78,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         22,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-15", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-02-16", ManPieceworkEditData{}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    45,
				Level3:                   0,
				Supermarket3Labels:       170,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  108,
				Mark2_J:                  20,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-17", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    507,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-02-18", ManPieceworkEditData{}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    296,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  84,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-19", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    507,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-02-20", ManPieceworkEditData{}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    247,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          26,
				Mark1_J:                  114,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-21", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    507,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    154,
				Level3:                   0,
				Supermarket3Labels:       67,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            49,
				SmallFruitMark1:          15,
				Mark1_J:                  102,
				Mark2_J:                  0,
				Mark3_J:                  2,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-22", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    0,
				Level3:                   507,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-02-23", ManPieceworkEditData{}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    40,
				Level3:                   0,
				Supermarket3Labels:       207,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            30,
				SmallFruitMark1:          35,
				Mark1_J:                  71,
				Mark2_J:                  0,
				Mark3_J:                  4,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-24", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    507,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    45,
				Level3:                   0,
				Supermarket3Labels:       226,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            20,
				SmallFruitMark1:          12,
				Mark1_J:                  80,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-25", ManPieceworkEditData{}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    56,
				Level3:                   0,
				Supermarket3Labels:       145,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            37,
				SmallFruitMark1:          59,
				Mark1_J:                  96,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-26", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-02-27", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    507,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    22,
				Level3:                   0,
				Supermarket3Labels:       125,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            16,
				SmallFruitMark1:          65,
				Mark1_J:                  87,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         42,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-02-28", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    507,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				SmallFruitMark1:          0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-01", ManPieceworkEditData{}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    5,
				Level3:                   0,
				Supermarket3Labels:       194,
				SmallFruit:               20,
				BigFruit:                 0,
				FlowersFruits:            55,
				SmallFruitMark1:          4,
				Mark1_J:                  48,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallBunchFruits:         6,
				BunchFruits:              65,
				FineBunchFruits:          26,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-03-02", ManPieceworkEditData{}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    1,
				Level3:                   0,
				Supermarket3Labels:       244,
				SmallFruit:               38,
				BigFruit:                 0,
				FlowersFruits:            22,
				Mark1_J:                  73,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallFruitMark1:          16,
				SmallBunchFruits:         0,
				BunchFruits:              2,
				FineBunchFruits:          17,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-03-03", ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    507,
				Level3:                   0,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            0,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallFruitMark1:          0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    18,
				Level3:                   0,
				Supermarket3Labels:       178,
				SmallFruit:               49,
				BigFruit:                 0,
				FlowersFruits:            62,
				Mark1_J:                  71,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallFruitMark1:          15,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{})
			fnWageDay("2022-03-04", ManPieceworkEditData{}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    0,
				Mark1Bar:                 0,
				Mark2:                    0,
				Mark3:                    11,
				Level3:                   0,
				Supermarket3Labels:       262,
				SmallFruit:               47,
				BigFruit:                 0,
				FlowersFruits:            18,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallFruitMark1:          35,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			}, ManPieceworkEditData{
				Time:                     time.Time{},
				Destination:              "",
				NumberOfCompleteVehicles: 0,
				FoamBox:                  0,
				PlasticFrame:             0,
				Mark1:                    13,
				Mark1Bar:                 0,
				Mark2:                    52,
				Mark3:                    162,
				Level3:                   18,
				Supermarket3Labels:       0,
				SmallFruit:               0,
				BigFruit:                 0,
				FlowersFruits:            25,
				Mark1_J:                  0,
				Mark2_J:                  0,
				Mark3_J:                  0,
				SmallFruitMark1:          0,
				SmallBunchFruits:         0,
				BunchFruits:              0,
				FineBunchFruits:          0,
				SweetBunchFruits:         0,
				BunchFruitsAA:            0,
				AAA:                      0,
				TurnoverBasket:           0,
				ElectronicCommerce:       0,
				Carpooling:               0,
				Note:                     "",
			})
			fnWageDay("2022-03-05", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-06", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-07", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-08", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-09", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-10", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-11", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-12", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-13", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-14", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-15", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-16", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-17", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-18", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-19", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-20", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-21", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-22", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-23", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-24", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-25", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-26", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-27", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-28", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-29", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-30", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-03-31", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-04-01", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-04-02", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-04-03", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-04-04", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})
			fnWageDay("2022-04-05", ManPieceworkEditData{}, ManPieceworkEditData{}, ManPieceworkEditData{})

			休息天数 := 0
			总车数 := 0
			总天数 := all.LenChildren()
			all.Walk(func(node *widget.Node[ManPieceworkEditData]) {
				if node.Data.Note == "没发车" {
					休息天数++
				}
				if node.Data.NumberOfCompleteVehiclesSum() > 0 {
					总车数++
				}
			})
			info = fmt.Sprintf("\t休息天数：%d\t总车数：%d\t总天数：%d", 休息天数, 总车数, 总天数)
		},
		JsonName:   "Piecework tomato loading",
		IsDocument: false,
	})
}
