// Code generated by 'yaegi extract github.com/ddkwork/ux/demo/erp/gongshi/sdk'. DO NOT EDIT.

package main

import (
	"github.com/ddkwork/ux/demo/erp/gongshi/sdk"

	"reflect"
)

func init() {
	Symbols["github.com/ddkwork/ux/demo/erp/gongshi/sdk/sdk"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewMemoryTable": reflect.ValueOf(sdk.NewMemoryTable),

		// type definitions
		"MemoryTable": reflect.ValueOf((*sdk.MemoryTable)(nil)),
	}
}
