// Code generated by 'yaegi extract github.com/ddkwork/ux/demo/erp/gongshi/sdk'. DO NOT EDIT.

package main

import (
	"github.com/ddkwork/golibrary/std/stream/uuid"
	"github.com/ddkwork/ux/demo/erp/gongshi/sdk"
	"go/constant"
	"go/token"
	"image/color"
	"reflect"
)

func init() {
	Symbols["github.com/ddkwork/ux/demo/erp/gongshi/sdk/sdk"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ContainerKeyPostfix":  reflect.ValueOf(constant.MakeFromLiteral("\"_container\"", token.STRING, 0)),
		"CountTableRows":       reflect.ValueOf(sdk.CountTableRows),
		"DefaultFilterOptions": reflect.ValueOf(&sdk.DefaultFilterOptions).Elem(),
		"ExampleUsage":         reflect.ValueOf(sdk.ExampleUsage),
		"FromJSON":             reflect.ValueOf(sdk.FromJSON),
		"NewContainerNode":     reflect.ValueOf(sdk.NewContainerNode),
		"NewFilterCondition":   reflect.ValueOf(sdk.NewFilterCondition),
		"NewFilterGroup":       reflect.ValueOf(sdk.NewFilterGroup),
		"NewNode":              reflect.ValueOf(sdk.NewNode),
		"NewTreeTable":         reflect.ValueOf(sdk.NewTreeTable),
		"OpContains":           reflect.ValueOf(sdk.OpContains),
		"OpEndsWith":           reflect.ValueOf(sdk.OpEndsWith),
		"OpEqual":              reflect.ValueOf(sdk.OpEqual),
		"OpGreaterEqual":       reflect.ValueOf(sdk.OpGreaterEqual),
		"OpGreaterThan":        reflect.ValueOf(sdk.OpGreaterThan),
		"OpIn":                 reflect.ValueOf(sdk.OpIn),
		"OpIsEmpty":            reflect.ValueOf(sdk.OpIsEmpty),
		"OpIsFalse":            reflect.ValueOf(sdk.OpIsFalse),
		"OpIsNotEmpty":         reflect.ValueOf(sdk.OpIsNotEmpty),
		"OpIsTrue":             reflect.ValueOf(sdk.OpIsTrue),
		"OpLessEqual":          reflect.ValueOf(sdk.OpLessEqual),
		"OpLessThan":           reflect.ValueOf(sdk.OpLessThan),
		"OpNotEqual":           reflect.ValueOf(sdk.OpNotEqual),
		"OpNotIn":              reflect.ValueOf(sdk.OpNotIn),
		"OpStartsWith":         reflect.ValueOf(sdk.OpStartsWith),
		"ToFloat":              reflect.ValueOf(sdk.ToFloat),

		// type definitions
		"CellData":           reflect.ValueOf((*sdk.CellData)(nil)),
		"ColumnConfig":       reflect.ValueOf((*sdk.ColumnConfig)(nil)),
		"ColumnDefinition":   reflect.ValueOf((*sdk.ColumnDefinition)(nil)),
		"FilterCondition":    reflect.ValueOf((*sdk.FilterCondition)(nil)),
		"FilterGroup":        reflect.ValueOf((*sdk.FilterGroup)(nil)),
		"FilterOperator":     reflect.ValueOf((*sdk.FilterOperator)(nil)),
		"FilterOptions":      reflect.ValueOf((*sdk.FilterOptions)(nil)),
		"Node":               reflect.ValueOf((*sdk.Node)(nil)),
		"SimpleTableModel":   reflect.ValueOf((*sdk.SimpleTableModel)(nil)),
		"TableData":          reflect.ValueOf((*sdk.TableData)(nil)),
		"TableRowConstraint": reflect.ValueOf((*sdk.TableRowConstraint)(nil)),
		"TableRowData":       reflect.ValueOf((*sdk.TableRowData)(nil)),
		"TreeTable":          reflect.ValueOf((*sdk.TreeTable)(nil)),

		// interface wrapper definitions
		"_TableRowConstraint": reflect.ValueOf((*_github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint)(nil)),
		"_TableRowData":       reflect.ValueOf((*_github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData)(nil)),
	}
}

// _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint is an interface wrapper for TableRowConstraint type
type _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint struct {
	IValue           interface{}
	WCanHaveChildren func() bool
	WCellDataForSort func(col int) string
	WChildren        func() []*sdk.Node
	WColumnCell      func(row int, col int, foreground color.Color, background color.Color, selected bool, indirectlySelected bool, focused bool) any
	WID              func() uuid.ID
	WIsOpen          func() bool
	WParent          func() *sdk.Node
	WSetChildren     func(children []*sdk.Node)
	WSetOpen         func(open bool)
	WSetParent       func(parent *sdk.Node)
}

func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint) CanHaveChildren() bool {
	return W.WCanHaveChildren()
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint) CellDataForSort(col int) string {
	return W.WCellDataForSort(col)
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint) Children() []*sdk.Node {
	return W.WChildren()
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint) ColumnCell(row int, col int, foreground color.Color, background color.Color, selected bool, indirectlySelected bool, focused bool) any {
	return W.WColumnCell(row, col, foreground, background, selected, indirectlySelected, focused)
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint) ID() uuid.ID {
	return W.WID()
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint) IsOpen() bool {
	return W.WIsOpen()
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint) Parent() *sdk.Node {
	return W.WParent()
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint) SetChildren(children []*sdk.Node) {
	W.WSetChildren(children)
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint) SetOpen(open bool) {
	W.WSetOpen(open)
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowConstraint) SetParent(parent *sdk.Node) {
	W.WSetParent(parent)
}

// _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData is an interface wrapper for TableRowData type
type _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData struct {
	IValue           interface{}
	WCanHaveChildren func() bool
	WCellDataForSort func(col int) string
	WChildren        func() []*sdk.Node
	WColumnCell      func(row int, col int, foreground color.Color, background color.Color, selected bool, indirectlySelected bool, focused bool) any
	WID              func() uuid.ID
	WIsOpen          func() bool
	WParent          func() *sdk.Node
	WSetChildren     func(children []*sdk.Node)
	WSetOpen         func(open bool)
	WSetParent       func(parent *sdk.Node)
}

func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData) CanHaveChildren() bool {
	return W.WCanHaveChildren()
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData) CellDataForSort(col int) string {
	return W.WCellDataForSort(col)
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData) Children() []*sdk.Node {
	return W.WChildren()
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData) ColumnCell(row int, col int, foreground color.Color, background color.Color, selected bool, indirectlySelected bool, focused bool) any {
	return W.WColumnCell(row, col, foreground, background, selected, indirectlySelected, focused)
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData) ID() uuid.ID {
	return W.WID()
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData) IsOpen() bool {
	return W.WIsOpen()
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData) Parent() *sdk.Node {
	return W.WParent()
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData) SetChildren(children []*sdk.Node) {
	W.WSetChildren(children)
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData) SetOpen(open bool) {
	W.WSetOpen(open)
}
func (W _github_com_ddkwork_ux_demo_erp_gongshi_sdk_TableRowData) SetParent(parent *sdk.Node) {
	W.WSetParent(parent)
}
