package main

import (
	"strings"

	"golang.org/x/exp/constraints"
)

// Code generated by GeneratedFile enum - DO NOT EDIT.

type DemoKind byte

const (
	TreeTableKind DemoKind = iota
	TreeKind
	Table2Kind
	TableKind
	ColorPickerKind
	CardKind
	SearchDropDownKind
	JsonTreeKind
	SvgButtonKind
	CodeEditorKind
	AsmViewKind
	LogViewKind
	ComBoxKind
	SplitViewKind
	MobileKind
	ListViewKind
	StructViewKind
	TerminalKind
	StackViewKind
	DockViewKind
	Gif123Kind
	HexEditorKind
	ImageEditorKind
	MediaPlayerKind
	MindKind
	PdfViewKind
	MapViewKind
	ThemeViewKind
	SettingsviewKind
	SliceviewKind
	XyzViewKind
	WebViewKind
	IconvgViewKind
	SvgViewKind
	CanvasViewKind
	PopMenuKind
	TooltipKind
	TextfieldKind
	MarkdownViewKind
	GomitmproxyKind
	HyperDbgKind
	VstartKind
	ExplorerKind
	DesignerKind
	AiChatKind
	EncodingTestKind
	GameControlFaceKind
	GithubKind
	GhipsKind
	TaskManagerKind
	GitlabKind
	SteamKind
	BuyTomatoesKind
	CcKind
	CryptKind
	DatabaseKind
	DatarecoveryKind
	HardInfoHookKind
	HardwareIndoKind
	DriverToolKind
	EnvironmentKind
	ErpKind
	FleetKind
	ImageConvertKind
	JetbraKind
	JiakaobaodianKind
	ManPieceworkKind
	MypanKind
	NetAdapterKind
	NetScanKind
	VisualStudiokitKind
	C2goKind
	VncKind
	TodoListKind
	DropFileKind
	DarkThemeKind
	InvalidDemoKind
)

func ConvertInteger2DemoKind[T constraints.Integer](v T) DemoKind {
	return DemoKind(v)
}

func (k DemoKind) AssertKind(kinds string) DemoKind {
	for _, kind := range k.Kinds() {
		if strings.ToLower(kinds) == strings.ToLower(kind.String()) {
			return kind
		}
	}
	return InvalidDemoKind
}

func (k DemoKind) String() string {
	switch k {
	case TreeTableKind:
		return "TreeTable"
	case TreeKind:
		return "Tree"
	case Table2Kind:
		return "Table2"
	case TableKind:
		return "Table"
	case ColorPickerKind:
		return "ColorPicker"
	case CardKind:
		return "Card"
	case SearchDropDownKind:
		return "SearchDropDown"
	case JsonTreeKind:
		return "JsonTree"
	case SvgButtonKind:
		return "SvgButton"
	case CodeEditorKind:
		return "CodeEditor"
	case AsmViewKind:
		return "AsmView"
	case LogViewKind:
		return "LogView"
	case ComBoxKind:
		return "ComBox"
	case SplitViewKind:
		return "SplitView"
	case MobileKind:
		return "Mobile"
	case ListViewKind:
		return "ListView"
	case StructViewKind:
		return "StructView"
	case TerminalKind:
		return "Terminal"
	case StackViewKind:
		return "StackView"
	case DockViewKind:
		return "DockView"
	case Gif123Kind:
		return "Gif123"
	case HexEditorKind:
		return "HexEditor"
	case ImageEditorKind:
		return "ImageEditor"
	case MediaPlayerKind:
		return "MediaPlayer"
	case MindKind:
		return "Mind"
	case PdfViewKind:
		return "PdfView"
	case MapViewKind:
		return "MapView"
	case ThemeViewKind:
		return "ThemeView"
	case SettingsviewKind:
		return "Settingsview"
	case SliceviewKind:
		return "Sliceview"
	case XyzViewKind:
		return "XyzView"
	case WebViewKind:
		return "WebView"
	case IconvgViewKind:
		return "IconvgView"
	case SvgViewKind:
		return "SvgView"
	case CanvasViewKind:
		return "CanvasView"
	case PopMenuKind:
		return "PopMenu"
	case TooltipKind:
		return "Tooltip"
	case TextfieldKind:
		return "Textfield"
	case MarkdownViewKind:
		return "MarkdownView"
	case GomitmproxyKind:
		return "Gomitmproxy"
	case HyperDbgKind:
		return "HyperDbg"
	case VstartKind:
		return "Vstart"
	case ExplorerKind:
		return "Explorer"
	case DesignerKind:
		return "Designer"
	case AiChatKind:
		return "AiChat"
	case EncodingTestKind:
		return "EncodingTest"
	case GameControlFaceKind:
		return "GameControlFace"
	case GithubKind:
		return "Github"
	case GhipsKind:
		return "Ghips"
	case TaskManagerKind:
		return "TaskManager"
	case GitlabKind:
		return "Gitlab"
	case SteamKind:
		return "Steam"
	case BuyTomatoesKind:
		return "BuyTomatoes"
	case CcKind:
		return "Cc"
	case CryptKind:
		return "Crypt"
	case DatabaseKind:
		return "Database"
	case DatarecoveryKind:
		return "Datarecovery"
	case HardInfoHookKind:
		return "HardInfoHook"
	case HardwareIndoKind:
		return "HardwareIndo"
	case DriverToolKind:
		return "DriverTool"
	case EnvironmentKind:
		return "Environment"
	case ErpKind:
		return "Erp"
	case FleetKind:
		return "Fleet"
	case ImageConvertKind:
		return "ImageConvert"
	case JetbraKind:
		return "Jetbra"
	case JiakaobaodianKind:
		return "Jiakaobaodian"
	case ManPieceworkKind:
		return "ManPiecework"
	case MypanKind:
		return "Mypan"
	case NetAdapterKind:
		return "NetAdapter"
	case NetScanKind:
		return "NetScan"
	case VisualStudiokitKind:
		return "VisualStudiokit"
	case C2goKind:
		return "C2go"
	case VncKind:
		return "Vnc"
	case TodoListKind:
		return "TodoList"
	case DropFileKind:
		return "DropFile"
	case DarkThemeKind:
		return "DarkTheme"
	default:
		return "InvalidDemoKind"
	}
}

func (k DemoKind) Keys() []string {
	return []string{
		"TreeTable",
		"Tree",
		"Table2",
		"Table",
		"ColorPicker",
		"Card",
		"SearchDropDown",
		"JsonTree",
		"SvgButton",
		"CodeEditor",
		"AsmView",
		"LogView",
		"ComBox",
		"SplitView",
		"Mobile",
		"ListView",
		"StructView",
		"Terminal",
		"StackView",
		"DockView",
		"Gif123",
		"HexEditor",
		"ImageEditor",
		"MediaPlayer",
		"Mind",
		"PdfView",
		"MapView",
		"ThemeView",
		"Settingsview",
		"Sliceview",
		"XyzView",
		"WebView",
		"IconvgView",
		"SvgView",
		"CanvasView",
		"PopMenu",
		"Tooltip",
		"Textfield",
		"MarkdownView",
		"Gomitmproxy",
		"HyperDbg",
		"Vstart",
		"Explorer",
		"Designer",
		"AiChat",
		"EncodingTest",
		"GameControlFace",
		"Github",
		"Ghips",
		"TaskManager",
		"Gitlab",
		"Steam",
		"BuyTomatoes",
		"Cc",
		"Crypt",
		"Database",
		"Datarecovery",
		"HardInfoHook",
		"HardwareIndo",
		"DriverTool",
		"Environment",
		"Erp",
		"Fleet",
		"ImageConvert",
		"Jetbra",
		"Jiakaobaodian",
		"ManPiecework",
		"Mypan",
		"NetAdapter",
		"NetScan",
		"VisualStudiokit",
		"C2go",
		"Vnc",
		"TodoList",
		"DropFile",
		"DarkTheme",
	}
}

func (k DemoKind) Kinds() []DemoKind {
	return []DemoKind{
		TreeTableKind,
		TreeKind,
		Table2Kind,
		TableKind,
		ColorPickerKind,
		CardKind,
		SearchDropDownKind,
		JsonTreeKind,
		SvgButtonKind,
		CodeEditorKind,
		AsmViewKind,
		LogViewKind,
		ComBoxKind,
		SplitViewKind,
		MobileKind,
		ListViewKind,
		StructViewKind,
		TerminalKind,
		StackViewKind,
		DockViewKind,
		Gif123Kind,
		HexEditorKind,
		ImageEditorKind,
		MediaPlayerKind,
		MindKind,
		PdfViewKind,
		MapViewKind,
		ThemeViewKind,
		SettingsviewKind,
		SliceviewKind,
		XyzViewKind,
		WebViewKind,
		IconvgViewKind,
		SvgViewKind,
		CanvasViewKind,
		PopMenuKind,
		TooltipKind,
		TextfieldKind,
		MarkdownViewKind,
		GomitmproxyKind,
		HyperDbgKind,
		VstartKind,
		ExplorerKind,
		DesignerKind,
		AiChatKind,
		EncodingTestKind,
		GameControlFaceKind,
		GithubKind,
		GhipsKind,
		TaskManagerKind,
		GitlabKind,
		SteamKind,
		BuyTomatoesKind,
		CcKind,
		CryptKind,
		DatabaseKind,
		DatarecoveryKind,
		HardInfoHookKind,
		HardwareIndoKind,
		DriverToolKind,
		EnvironmentKind,
		ErpKind,
		FleetKind,
		ImageConvertKind,
		JetbraKind,
		JiakaobaodianKind,
		ManPieceworkKind,
		MypanKind,
		NetAdapterKind,
		NetScanKind,
		VisualStudiokitKind,
		C2goKind,
		VncKind,
		TodoListKind,
		DropFileKind,
		DarkThemeKind,
	}
}

func (k DemoKind) PngFileName() string {
	switch k {
	case TreeTableKind:
		return "TreeTable"
	case TreeKind:
		return "Tree"
	case Table2Kind:
		return "Table2"
	case TableKind:
		return "Table"
	case ColorPickerKind:
		return "ColorPicker"
	case CardKind:
		return "Card"
	case SearchDropDownKind:
		return "SearchDropDown"
	case JsonTreeKind:
		return "JsonTree"
	case SvgButtonKind:
		return "SvgButton"
	case CodeEditorKind:
		return "CodeEditor"
	case AsmViewKind:
		return "AsmView"
	case LogViewKind:
		return "LogView"
	case ComBoxKind:
		return "ComBox"
	case SplitViewKind:
		return "SplitView"
	case MobileKind:
		return "Mobile"
	case ListViewKind:
		return "ListView"
	case StructViewKind:
		return "StructView"
	case TerminalKind:
		return "Terminal"
	case StackViewKind:
		return "StackView"
	case DockViewKind:
		return "DockView"
	case Gif123Kind:
		return "Gif123"
	case HexEditorKind:
		return "HexEditor"
	case ImageEditorKind:
		return "ImageEditor"
	case MediaPlayerKind:
		return "MediaPlayer"
	case MindKind:
		return "Mind"
	case PdfViewKind:
		return "PdfView"
	case MapViewKind:
		return "MapView"
	case ThemeViewKind:
		return "ThemeView"
	case SettingsviewKind:
		return "Settingsview"
	case SliceviewKind:
		return "Sliceview"
	case XyzViewKind:
		return "XyzView"
	case WebViewKind:
		return "WebView"
	case IconvgViewKind:
		return "IconvgView"
	case SvgViewKind:
		return "SvgView"
	case CanvasViewKind:
		return "CanvasView"
	case PopMenuKind:
		return "PopMenu"
	case TooltipKind:
		return "Tooltip"
	case TextfieldKind:
		return "Textfield"
	case MarkdownViewKind:
		return "MarkdownView"
	case GomitmproxyKind:
		return "Gomitmproxy"
	case HyperDbgKind:
		return "HyperDbg"
	case VstartKind:
		return "Vstart"
	case ExplorerKind:
		return "Explorer"
	case DesignerKind:
		return "Designer"
	case AiChatKind:
		return "AiChat"
	case EncodingTestKind:
		return "EncodingTest"
	case GameControlFaceKind:
		return "GameControlFace"
	case GithubKind:
		return "Github"
	case GhipsKind:
		return "Ghips"
	case TaskManagerKind:
		return "TaskManager"
	case GitlabKind:
		return "Gitlab"
	case SteamKind:
		return "Steam"
	case BuyTomatoesKind:
		return "BuyTomatoes"
	case CcKind:
		return "Cc"
	case CryptKind:
		return "Crypt"
	case DatabaseKind:
		return "Database"
	case DatarecoveryKind:
		return "Datarecovery"
	case HardInfoHookKind:
		return "HardInfoHook"
	case HardwareIndoKind:
		return "HardwareIndo"
	case DriverToolKind:
		return "DriverTool"
	case EnvironmentKind:
		return "Environment"
	case ErpKind:
		return "Erp"
	case FleetKind:
		return "Fleet"
	case ImageConvertKind:
		return "ImageConvert"
	case JetbraKind:
		return "Jetbra"
	case JiakaobaodianKind:
		return "Jiakaobaodian"
	case ManPieceworkKind:
		return "ManPiecework"
	case MypanKind:
		return "Mypan"
	case NetAdapterKind:
		return "NetAdapter"
	case NetScanKind:
		return "NetScan"
	case VisualStudiokitKind:
		return "VisualStudiokit"
	case C2goKind:
		return "C2go"
	case VncKind:
		return "Vnc"
	case TodoListKind:
		return "TodoList"
	case DropFileKind:
		return "DropFile"
	case DarkThemeKind:
		return "DarkTheme"
	default:
		return "InvalidDemoKind"
	}
}
